### PR TITLE
Fixes #157: Changed os-level dependency 'zip' and 'unzip' to 'tar' (master)

### LINKED ISSUE #157: Setup script still requires zip/unzip but should require tar
At some point before releasing 0.8.1, the distribution archive was changed to be tar.gz again, like it was in 0.7.

However, it was forgotten to remove the os-level dependencies to zip/unzip in the setup file, and to add one for tar instead.

### PR DESCRIPTION
**Pull request by andy-maier**
This PR contains the same change as PR #157, but targets the master branch, instead.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
What are we going to do about windows since that is largely zip based?

**Comment by andy-maier** [comment]
v0.7 had an installer .exe for Windows as the release vehicle. It can be built on Windows with `make buildwin`, but I have not tested it recently. We should probably have an issue for testing it on Windows, but this change here does not affect iIndows, IMO.

**Comment by KSchopmeyer** [comment]
+1

**Comment by andy-maier** [comment]
+1

**Pull request merged**
