### PR TITLE
Fixes #407: Added context manager capability to WBEMSubscriptionManager

### LINKED ISSUE #407: Automatic cleanup of owned destinations, filters, subscriptions
Pywbem takes no part in any cleanup of subscriptions and filters that might be left in the server when the listener is stopped without removing these subscriptions/filters.

We do not have a way to identify them as created by our client, etc. so they could be eliminated subsequent at a later time.

At this point I just want to start the conversation since after a bunch of testing where we were terminating the test programs early we ended up with a bunch of outdated filters in the server all with the name cimfilter<uid>

### PR DESCRIPTION
**Pull request by andy-maier**
Also, corrected DSP1054 references in the docs of `WBEMSubscriptionManager`.

The only testcase is in `run_cim_operations.py`, and I did not test with it.

### CODE REVIEW

**Comment by andy-maier** [comment]
Karl, can you run the `run_cim_operations.py` test in your environment?

**Comment by KSchopmeyer** [comment]
Comments:

1. Comment on the doc
    with WBEMSubscriptionManager('fred') as subscription_manager:
        server1_id = subscription_manager.add_server(server1)
    # exit method automatically calls remove_all_servers()

a. add a line with . . . for other work to be done

b. Add to comment on last line " which removes all owned filters, etc.

2. Question. Is there any reason to further docment what a context manager does either on line
181 (class description) or line 239 (the _enter_ function)?? I.e. are we going to get users who do
not clearly understand what a context manager is?

**Comment by KSchopmeyer** [comment]
running run_cim_operation.py I get the following error:

======================================================================
ERROR: test_subscription_context_manager (__main__.PyWBEMListenerClass)
Test that the WBEMSUbscriptionmanager class can be used as a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 3673, in test_subscription_context_manager
    sub_mgr.remove_all_servers()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_subscription_manager.py", line 424, in remove_all_servers
    self.remove_server(server.url)
AttributeError: 'str' object has no attribute 'url'

NOTE: I only tested this shortly before the meeting and for some reason am getting issue with not enough indications received in some of the other tests but not  yet sure why.  However, those are count errors, this is a syntax/semantics issue.

**Comment by andy-maier** [comment]
In addition, there is an error in `remove_server()` where it deletes the entries in the various dictionaries. Python does not allow deleting items in a dictionary while iterating over it. So the list of keys to iterate over needs to be instantiated into a separate list object that remains unchanged when deleting the items. The `list()` constructor is needed to make that work on Python 3, because `keys()` returns an iterator in Python 3. Fixed that as well.

**Comment by andy-maier** [comment]
Karl,
this PR is now ready for a retest with `run_cim_operations.py`.

**Comment by andy-maier** [comment]
+1

**Comment by andy-maier** [comment]
Commit dff3989 is a fix that should be rolled back into the 0.9 stream.

**Comment by andy-maier** [comment]
Rebased on master after merging PR #604, to fix the Sphinx build issue on Python 2.6.

**Comment by andy-maier** [comment]
We agreed to merge this one, and to do the test as part of PR #607.

**Pull request merged**
