### PR TITLE
[WIP] Included vendored packages: nocasedict, nocaselist, yamlloader

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

**Note: This PR is ready for review, but merging needs to wait for resolution of discussion in issue #2434**

TODOs:
* The import statements in the pywbem code for the vendored packages had to be changed to get them from the `_vendor` directory. It would be nicer if there could be an import approach that is common regardless of whether the package is actually vendored or not.
* If the nocaselist and nocasedict packaging requests for Fedora get approved, remove them again from this PR.
* Use a released version of vendorize that fixes issue https://github.com/mwilliamson/python-vendorize/issues/13. Currently, a version from my fork is used.
* Use a released version of yamlloader for Python 2.7 that fixes issue https://github.com/Phynix/yamlloader/issues/24. Currently, a version from my fork is used.

### CODE REVIEW

**Review by KSchopmeyer — APPROVED** [review]

**Comment by KSchopmeyer** [comment]
I approve this but what worrys me is that this is going to be a trend with a couple of vendors like Redhat driving a lot of the direction of things like python by setting their special rules.  Thus, vendorize may become more and more popular leading to larger packages and fewer uses of these vendorized packages, in turn leading to false statistics about the use of these vendorized packages.  Oh well.

**Comment by andy-maier** [comment]
Added the yamlloader package also as a vendored package. See Tony's comment in issue #2434 .

**Comment by andy-maier** [comment]
Using the vendorize package from my fork with a fix for its issue https://github.com/mwilliamson/python-vendorize/issues/13

**Comment by andy-maier** [comment]
Since there is an outlook that the nocasedict and nocaselist Python packages can become OS-level packages, this PR has been removed from 1.3.0 again. It remains open until the packaging question is resolved.

**Comment by andy-maier** [comment]
Dropped, see #2434.

**Pull request closed without merging**
