### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by andy-maier**
Please approve the release of pywbem 1.1.0

### CODE REVIEW

**Comment by andy-maier** [comment]
Waiting for resolution of #2485

**Comment by andy-maier** [comment]
Waiting for merge of PR #2488, then rebase.

**Review by KSchopmeyer — APPROVED** [review]

**Review by KSchopmeyer — APPROVED** [review]

**Comment by andy-maier** [comment]
Waiting for completion of the manual-ci-run branch, then continue release process.

**Comment by andy-maier** [comment]
Waiting for pywbemtools 0.7.3 which has a fix to accomodate pywbem 1.1.0.

**Comment by andy-maier** [comment]
Pywbemtools 0.7.3 has been released. Resuming this PR now.

**Pull request merged**
