### PR TITLE
Clean up pylint for selected modules

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Cleaned up cim_constants.py, cim_http.py and cim_types.py.  Note that this does not remove all pylint issues but significantly reduces the number for these modules.

The end result is:

cim_constants                          0
cim_types                                 0
pywbem.cim_http               Total: 24
---------------------------------------
(protected-access)                   3
(line-too-long)                          7
(unnecessary-lambda)            1
(no-member)                          5
(fixme)                                    2
(not-an-iterable)                     1
(redefined-variable-type)        1
(deprecated-lambda)              1
(bad-builtin)                            1
(dangerous-default-value)      1
(using-constant-test)               1
---------------------------------------

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
hide a couple more pylint msgs for the whole module:

disable=non-parent-init-called,super-init-not-called

with TODO to investigate futher.

The total oustanding pylint msgs for thee files changed in this branch is now:
************* Module pywbem.cim_xml
W: 23, 0: TODO: Sort this issue out and see if we need to fix KS_TODO. These (fixme)
R:180, 8: Redefinition of node type from xml.dom.minidom.CDATASection to xml.dom.minidom.Text (redefined-variable-type)
W:311,29: Redefining built-in 'type' (redefined-builtin)
W:311, 4: Dangerous default value {} as argument (dangerous-default-value)
R:339,16: Redefinition of xval type from pywbem.cim_xml.VALUE_ARRAY to pywbem.cim_xml.VALUE (redefined-variable-type)
W:359, 4: Dangerous default value {} as argument (dangerous-default-value)
W:751, 4: Dangerous default value [] as argument (dangerous-default-value)
W:751, 4: Dangerous default value [] as argument (dangerous-default-value)
W:751, 4: Dangerous default value [] as argument (dangerous-default-value)
W:769, 4: Dangerous default value [] as argument (dangerous-default-value)
W:769, 4: Dangerous default value [] as argument (dangerous-default-value)
W:797,29: Redefining built-in 'type' (redefined-builtin)
W:844,29: Redefining built-in 'type' (redefined-builtin)
W:844, 4: Dangerous default value [] as argument (dangerous-default-value)
W:903,29: Redefining built-in 'type' (redefined-builtin)
W:903, 4: Dangerous default value [] as argument (dangerous-default-value)
W:943, 4: Dangerous default value [] as argument (dangerous-default-value)
W:977, 4: Dangerous default value [] as argument (dangerous-default-value)
W:977, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1005,29: Redefining built-in 'type' (redefined-builtin)
W:1005, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1024, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1044,29: Redefining built-in 'type' (redefined-builtin)
W:1044, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1066, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1238, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1262, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1282, 4: Dangerous default value [] as argument (dangerous-default-value)
W:1479, 4: Dangerous default value [] as argument (dangerous-default-value)
************* Module pywbem.cim_http
W:405, 0: TODO: Currently disabled, figure out how to reenable (fixme)
W:561, 0: TODO: Verify these errno numbers on Windows vs. Linux (fixme)
W:243,16: Access to a protected member _path of a client class (protected-access)
W:246,12: Access to a protected member _path of a client class (protected-access)
W:247,11: Access to a protected member _path of a client class (protected-access)
W:250, 0: Dangerous default value [] as argument (dangerous-default-value)
E:335,15: Instance of 'HTTPBaseConnection' has no 'sock' member (no-member)
E:336,19: Instance of 'HTTPBaseConnection' has no 'auto_open' member (no-member)
E:337,20: Instance of 'HTTPBaseConnection' has no 'connect' member (no-member)
E:340,15: Instance of 'HTTPBaseConnection' has no 'debuglevel' member (no-member)
E:342,12: Instance of 'HTTPBaseConnection' has no 'sock' member (no-member)
W:405,16: Using a conditional statement with a constant value (using-constant-test)
R:394,16: Redefinition of self.sock type from socket._socketobject to M2Crypto.SSL.Connection.Connection (redefined-variable-type)
E:522,34: Non-iterable value local_auth_header is used in an iterating context (not-an-iterable)
W:536,29: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:536,29: map/filter on lambda could be replaced by comprehension (deprecated-lambda)
W:536,33: Lambda may not be necessary (unnecessary-lambda)

**Comment by KSchopmeyer** [comment]
+1

**Comment by KSchopmeyer** [comment]
voted yes to commit this change

**Comment by andy-maier** [comment]
+1

**Pull request merged**
