### PR TITLE
0.15: Removed the use of the 'pbr' package

### PR DESCRIPTION
**Pull request by andy-maier**
Rolls back PR #1876 into 0.15.0.

### CODE REVIEW

**Comment by andy-maier** [comment]
Karl and I discussed the question on 0.15, and we agreed that this should go into a 0.15.0 version.

**Comment by KSchopmeyer** [comment]
Update when the version 1.0.0 version released. Otherwise no comments.

**Comment by andy-maier** [comment]
Applied review comments fro 1.0.0 version here as well.

**Comment by andy-maier** [comment]
Rebased on the new 0.15.0 version.

**Comment by andy-maier** [comment]
This PR was re-targeted to 0.15.0 from a content perspective, but it was forgotten that it still targeted 0.14. It was merged by mistake, and undone by force-push. As a result, it did not go in.

PR #1882 rolls this change correctly into 0.15.0.

**Pull request merged**
