### PR TITLE
Fixes #184: Minor doc updates.

### LINKED ISSUE #184: Minor doc updates
This issue collects some random issues on the docs:

DONE means there is a PR that addresses the item.
MOVED means the item has been moved to another issue.
- Update change log.
- DONE: Introduction in `intro.rst`:
  - DONE: Clumsy wording of component descriptions in Introduction.
  - DONE: Add compiler API to list of components in Introduction.
  - DONE: Add term "string" for ("unicode string" or "byte string") and use that throughout.
- DONE: Change "list" to "iterable" in the types of input parms, throughout.
- DONE: Remove "currently" and "at this time", throughout.
- DONE: Description of "CIM data types" in `pywbem/__init__.py` could be straightened out to say "Python objects for representing values of CIM data types", and in intro of `pywbem/cim_types.py`.
- DONE: Class `WBEMConnection`:
  - MOVED to #196: Make `methodcall()` and `imethodcall()` non-public (by adding underscore).
  - DONE: In introduction:
    - DONE: Recommendation for treatment of exceptions that are considered programming errors could be straightened out where it distinguishes between user-generated and pywbem-generated.
  - DONE: in `__init__()` description:
    - DONE: Type "number" for `timeout` parameter: Does it allow just for "int", or for any number type?
    - DONE: In parameter description, detail that the instance variables set from the parameters are public.
    - DONE: In description of `last_raw_reply`, remove excess text at the end.
    - In description of `url`, add supported formats and examples.
    - DONE: In description of `verify_callback`:
      - DONE: typo "alreay"
      - DONE: improve how M2Crypto is mentioned (it is only used in Python 2).
      - DONE: move description of callback function's interface into its own place.
  - DONE: In all references to CIM-XML operation names, add "see DSP0200" (e.g. in "This method performs the EnumerateInstanceNames operation.")
  - DONE: In short descriptions of operation methods, add "in a namespace" where it makes sense.
  - DONE: In descriptions of `IncludeQualifiers` on most operations, fix grammar error "qualifiers not included".
  - DONE: In `GetInstance()`: Descriptions of `LocalOnly` and `IncludeClassOrigin` talk about instances in plural.
  - MOVED to #197: In `ModifyInstance()`: In `ModifiedInstance`, the instance to be modified is explained just based upon its namespace. That could be straightened out to be stated based upon the entire path. However, the namespace is called out in order to be clear that the connection default namespace does not play any role here. Second: In association ops, default namespace of the connection is used if the input instance path does not specify one. This is inconsistent with ModifyInstance. Come to one consistent approach.
  - MOVED to #197: In operations that provide an instance path or class path, the host component of the path is not passed on to the server, but that is not specifically described anywhere. Should it?
  - MOVED to #197: In `CreateInstance()`, the creation class name is stated to be taken from the `classname` variable of the provided new instance object, while the namespace is taken from the `path` variable of that object. Why the inconsistency?
  - MOVED to #197: In `EnumerateInstanceNames()` and `EnumerateInstances()`: What should we say about the presence of namespace and host in the returned instance paths?
  - DONE: In `AssociatorNames()` and other association ops:
    - DONE: Simplify short description by making two sentences, for instances and classes.
    - DONE: For `None` in filter parms, change "no filtering" to "no such filtering".
  - MOVED to #197: In `AssociatorNames()` and other association ops: What should we say about the presence of namespace and host in the returned instance/class paths?
  - MOVED to #197: In ops that return instances: What should we say about the presence of the path in the instances?
  - DONE: In ops that have an `ObjectName` parm (i.e. association ops and invoke method): Clarify that when a CIMClassName object is used as an argument, its namespace is used, if not None.
  - DONE: In `InvokeMethod()`, returned output parameters: Clarify that the case of the parameter names is preserved, and remove "CIM" before "parameter".
  - DONE: In `ExecQuery()`, `QueryLanguage` parameter: Add the strings for WQL and CQL as examples.
  - DONE: In `ModifyClass()` and `CreateClass()`: The input class is a `CIMClass` object which does not have a path. Remove the statement about path being ignored.
  - DONE: In `DeleteClass()`, `GetClass()`, `EnumerateInstance*()` and `EnumerateClass*()` : If the `ClassName` parameter is a `CIMClassName` object, its namespace (and host) are ignored. `DeleteClass()` does not scope its statement to just that type of input object, and the other ops don't even mention that at all.
- DONE: In `CIMInstanceName` ctor, `keybindings` parameter: "dict" type should become a link.
- DONE: In most CIM object classes:
  - DONE: Change ", see the corresponding constructor parameter" to ". For details, see ...".
  - DONE: Use of "for" vs. "of": make consistent.
  - DONE: Descriptions of meaning of `None` is sometimes missing.
  - DONE: In `tomof()`: Clean up the wording, e.g. to: "Return a unicode string that is a MOF fragment with the method declaration represented by the CIMMethod object."

### PR DESCRIPTION
**Pull request by andy-maier**
The PR includes those things from issue #184 where supposedly no discussion is needed.

Please review.

* In Introduction in `intro.rst`:
  - Clumsy wording of component descriptions in Introduction.
  - Add compiler API to list of components in Introduction.
  - Add term "string" for ("unicode string" or "byte string") and use that throughout.
* Change "list" to "iterable" in the types of input parms, throughout.
* Remove "currently" and "at this time", throughout.
* Description of "CIM data types" in `pywbem/__init__.py` could be straightened out to say "Python objects for representing values of CIM data types", and in intro of `pywbem/cim_types.py`.
* Class `WBEMConnection`:
  - In introduction:
    - Recommendation for treatment of exceptions that are considered programming errors could be straightened out where it distinguishes between user-generated and pywbem-generated.
  - In `__init__()` description:
    - Type "number" for `timeout` parameter: Does it allow just for "int", or for any number type? Answer: It allows for integer and float.
    - In parameter description, detail that the instance variables set from the parameters are public.
    - In description of `last_raw_reply`, remove excess text at the end.
    - In description of `verify_callback`:
      - typo "alreay"
      - improve how M2Crypto is mentioned (it is only used in Python 2).
  - In all references to CIM-XML operation names, add "see DSP0200" (e.g. in "This method performs the EnumerateInstanceNames operation.")
  - In short descriptions of operation methods, add "in a namespace" where it makes sense.
  - In descriptions of `IncludeQualifiers` on most operations, fix grammar error "qualifiers not included".
  - In `GetInstance()`: Descriptions of `LocalOnly` and `IncludeClassOrigin` talk about instances in plural.
  - In `AssociatorNames()` and other association ops:
    - Simplify short description by making two sentences, for instances and classes.
    - For `None` in filter parms, change "no filtering" to "no such filtering".
  - In ops that have an `ObjectName` parm (i.e. association ops and invoke method): Clarify that when a CIMClassName object is used as an argument, its namespace is used, if not None.
  - In `InvokeMethod()`, returned output parameters: Clarify that the case of the parameter names is preserved, and remove "CIM" before "parameter".
  - In `ExecQuery()`, `QueryLanguage` parameter: Add the strings for WQL and CQL as examples.
  - In `ModifyClass()` and `CreateClass()`: The input class is a `CIMClass` object which does not have a path. Remove the statement about path being ignored.
  - In `DeleteClass()`, `GetClass()`, `EnumerateInstance*()` and `EnumerateClass*()` : If the `ClassName` parameter is a `CIMClassName` object, its namespace (and host) are ignored. `DeleteClass()` does not scope its statement to just that type of input object, and the other ops don't even mention that at all.
* In `CIMInstanceName` ctor, `keybindings` parameter: "dict" type should become a link.
* In most CIM object classes:
  - Change ", see the corresponding constructor parameter" to ". For details, see ...".
  - Use of "for" vs. "of": make consistent.
  - Descriptions of meaning of `None` is sometimes missing.
  - In `tomof()`: Clean up the wording, e.g. to: "Return a unicode string that is a MOF fragment with the method declaration represented by the CIMMethod object."

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
I only gave this one a short overview;

I will +1 it but if you want to wait until tonight I will review in detail

Off to cross nevada

**Comment by andy-maier** [comment]
Will wait for your more detailed review, then.

**Comment by andy-maier** [comment]
Rebased, to update the dist archive.

**Comment by KSchopmeyer** [comment]
I do have a couple of comments:
1. intro.rst.  in section on WBEM client library you removed "provides an API". That is the one place it makes sense to define it as an API or set of APIs, etc. We do ref  this as an API elsewhere in to doc.

2. I wish we could get away from referencing element back to the minidom since we really want to get rid of the minidom in favor of a sax parser.  Probably not possible right now since we need to use that knowledge

3. cim_+obj.py. Statement in cimpropery class "        For details, see the corresponding constructor parameter." and next sentence seem to clash

got through cim_obj.py and will continue tonight.

**Comment by andy-maier** [comment]
Rebased to resolve merge conflict in a docstring in `pywbem/mof_compiler.py`.

**Comment by andy-maier** [comment]
On your comments:

1. On removal of  "provides an API" in section on WBEM client library in `intro.rst`:
   I thought it would be too close to being an API (which would not be correct), but your comment made me think about it again, and I think you are right and it should say that. After all, the main purpose of a library is to provide an API. Will change accordingly.

2. On referencing `Element` in minidom:
  That's what pywbem is using currently as the result of a function that is an official part of the external API. I think that is sufficient for describing that this is the case. If we change the returned objects to something else, we need to carefully judge the compatibility question. If there is a class defining the common behaviour of different flavors of XML Element classes, I could be convinced to reference that class. Do you know of such a class?

3. On statement in `CIMProperty` docstring: "For details, see the corresponding constructor parameter.":
   Is this about the `value` instance variable? The intention is that the sentence after the quoted sentence describes the exception to the description of the corresponding ctor parameter. If this comes across too complicated, we could simply describe what it means without referencing the ctor parameters. Let me know.

**Comment by KSchopmeyer** [comment]
Forget my comment about minidom and parsing.  The light dawned after I started driving this morning. The real issue is that we are committing to a minidom object output for tocimxml.  If we should decide to change the xml holder (something other than minidom) in the future, we are stuck with that interface. Further, the user has to convert anyway with a minidom function to get text output.

Not part of this bug but shouldn't the public function be one that outputs xml text??? Discussion wed.

**Comment by andy-maier** [comment]
I agree on what the issue is. By the way, we are returning instances of subclasses of Element, which are our own, and the only reason I was referring to Element is that I did not want all of these subclasses to be part of the external API, just because of this one function. 

On returning XML text: That would solve the Element & subclass problem. However, it would be an incompatible change.

**Comment by KSchopmeyer** [comment]
How about a change to just leave this one alone and not that it should not have been public and create another one that internally just adds the toprettyxml().  That also keeps people from having to dig up that function.

Note that this should be separate issue in any case.

**Comment by andy-maier** [comment]
I created issue #208 for the new `tocimxmlstr()` methods. Please review it there.

**Comment by andy-maier** [comment]
Karl, from your comments, only 3. is still open.

**Comment by KSchopmeyer** [comment]
Went through remainder, no more comments. The comment 3 above:

One sentence says see the corresponding constructor parameter and the next sentence qualifies that for two particular types.

a. Suggest 
For details see the corresponding CIM data type constructor except for the following special case:
   - string and char16 - this instance variable will be "term:`unicode string` even when specified as at :term: `byte string`

Sorry to take so long with this one.

**Comment by KSchopmeyer** [comment]
+1

**Comment by andy-maier** [comment]
Karl,
I made another change that addresses your comment 3 by replacing the generic references to the descriptions of ctor parameters, with a copy of th descriptions, if it was short enough to warrant that. For longer things, there is still a "see details", but it is now for a specific purpose, like "For details on the dictionary items, see ...".

Also, the simplification "or `None`" was often used in instance variable descriptions. that has also been made specific.

The changes warrant another review (e.g. build the docs, and look at sections "Variables" and "Parameters" of all CIM object classes).

**Comment by andy-maier** [comment]
+1

**Comment by andy-maier** [comment]
Addressed two more issues. The issue #184 is now completely addressed with this PR.

**Comment by andy-maier** [comment]
+1

**Comment by andy-maier** [comment]
Rebased to resolve merge conflicts.

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
