### PR TITLE
Fixes #895: Fixed local authentication for OpenWBEM and OpenPegasus

### LINKED ISSUE #895: Local authentication is broken
Following up on the pylint issue reported in cim_http.py(721):
```
E:726,30: Non-iterable value local_auth_header is used in an iterating context (not-an-iterable)
```
revealed a larger issue, namely that the code path for local authentication for OpenWBEM and OpenPegasus can never be reached, and the credential-based Basic authentication is always used.

From cim_http.py, ca. line 721:
```
    if local_auth_header is not None:
        # The following pylint stmt disables a false positive, see
        # https://github.com/PyCQA/pylint/issues/701
        # TODO 3/16 AM: Track resolution of this Pylint bug.
        # pylint: disable=not-an-iterable
        header_tuples.append(*local_auth_header)
    elif creds is not None:
        auth = '%s:%s' % (creds[0], creds[1])
        auth64 = _ensure_unicode(base64.b64encode(
            _ensure_bytes(auth))).replace('\n', '')
        header_tuples.append(('Authorization', 'Basic %s' % auth64))
    elif locallogin is not None:
        header_tuples.append(('PegasusAuthorization',
                              'Local "%s"' % locallogin))
```
The code above is *outside* of the retry loop in which a returned HTTP status 401 is handled automatically for some cases by setting `local_auth_header`, so the condition on the first `if` statement never becomes true.

In addition, the code contains a bug in that `if`-statement in the statement:
```
header_tuples.append(*local_auth_header)
```
because `local_auth_header` is set to a tuple(header_name, header_value), so the line shown above provides append() with two arguments, resulting in TypeError being raised.

The first bug was introduced in PR #366 (which went into pywbem 0.9.0), and because we test at a higher level in pywbem, it was not found. The second bug has always been there. Looking into our test coverage reveals that this line is in fact never executed, e.g. results from a recent run: https://coveralls.io/builds/14694937/source?filename=pywbem%2Fcim_http.py#L723

There is also some good news about this: It seems that nobody uses local authentication, because the second bug has always been there (I checked back to 0.7.0, i.e. https://github.com/pywbem/pywbem/blob/ab9ef9a332e7e32d02c7cc2861ab0f6e2c05d04c/trunk/cim_http.py#L186).

### PR DESCRIPTION
**Pull request by andy-maier**
For details, see commit message.
Ready for review and merge.
This change should be tested against a real environment, and local authentication should be used.
**Note:** PR #922 is on top of this PR and has changes in exception handling. The two changes can be tested together by using PR #922.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Here is an OpenPegasus trace of some of the errors

**Comment by KSchopmeyer** [comment]
1514510701s-838643us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 380
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: AssociatorNames
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="AssociatorNames"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ObjectName"><CLASSNAME NAME="CIM_BlanBlahBlah"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-839142us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-845871us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510701s-871826us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 388
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: EnumerateInstanceNames
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="EnumerateInstanceNames"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="CIM_ComputerSystem"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-872111us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-873177us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510701s-897767us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 382
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: AssociatorNames
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="AssociatorNames"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ObjectName"><CLASSNAME NAME="CIM_ComputerSystem"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-897930us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-899217us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510701s-923957us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 369
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: GetClass
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="PyWBEM_Person"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-924256us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-926006us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510701s-950661us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 369
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: GetClass
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="PyWBEM_Person"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-950933us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-951918us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510701s-977211us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 369
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: GetClass
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="PyWBEM_Person"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510701s-977500us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.


1514510701s-978532us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2275]: 
1514510702s-3188us: XmlIO [6176:139860854400896:HTTPConnection.cpp:2319]: 
POST /cimom HTTP/1.1
Host: sheldon:5988
Accept-Encoding: identity
Content-type: application/xml%3B%20charset%3D%22utf-8%22
Content-length: 369
Authorization: BasicXXXXXXXXXXXXX
CIMOperation: MethodCall
CIMMethod: GetClass
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="PyWBEM_Person"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1514510702s-3472us: XmlIO [6176:139860854400896:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
PGErrorDetail: HTTP%20Content-Type%20header%20error.

**Comment by andy-maier** [comment]
I have a suspicion about the reason:
Before this change, only additional header fields that were passed in to imethodcall or methodcall were percent-encoded (see [previous cim_operations.py(738)](https://github.com/pywbem/pywbem/pull/896/files#diff-820085a6a6ae5cea06a2288bf6be587eL738)).
With this change, all header fields are percent-encoded (see [changed cim_operations.py(761)](https://github.com/pywbem/pywbem/pull/896/files#diff-820085a6a6ae5cea06a2288bf6be587eR761)).
So the "Content-type" field which Pegasus complains about is now percent-encoded and wasn't previously.

What I don't understand quite, is the percent-encoding in the Pegasus log you show. For example, the value of the `PGErrorDetail` header field is shown with percent-encoding: `HTTP%20Content-Type%20header%20error` but this is a server-side log of a header field the server generated, so this cannot have anything to do with pywbem. Can you please have a look into why that is shown with percent-encodings?

I have a further suspicion, namely that HTTP header fields ought not to be percent-encoded at all. Reading RFC2616, I don't find an explicit statement about whether or not header fields should be percent-encoded. However, the only mentioning of percent-encoding in RFC2616 is for the URI (it can be found by searching for `%` or for `HEX HEX`). The definition of `field-content` in RFC2616 does not mention percent-encoding at all. This leads me to believe that percent-encoding for header field names or values is not permitted as per RFC2616. There are some StackOverflow articles related to that:

* [Is it appropriate or necessary to use percent-encoding with HTTP Headers?](https://stackoverflow.com/q/23215227)
* [What character encoding should I use for a HTTP header?](https://stackoverflow.com/q/4400678)
* [What encoding should I use for HTTP Basic Authentication?](https://stackoverflow.com/q/7242316)

I answered on the first one of them, stating my understanding.

If that understanding is correct, then we should remove the code that percent-encodes the headers in pywbem, and you should double check why the Pegasus `PGErrorDetail` header field is shown with percent-encoding in its log.

Another question would be whether a HTTP consumer should tolerate and unescape percent-escaped field names or values.

**Comment by andy-maier** [comment]
The last commit fixes that error, as described above.

**Comment by andy-maier** [comment]
There is one **discussion point** on this entire change:

* One motivation for moving the construction of the headers outside of the retry loop back in v0.9.0 was to have all headers constructed when recording them. Moving that back into the retry loop in order to pick up a changed local_auth_header causes only the CIM-XML extension headers to be recorded, but not the standard headers. At least in the last commit of this PR. Discuss what we expect from the HTTP recording, not only in terms of which header fields it shows, but also whether it shows the retries.

**Comment by andy-maier** [comment]
I decided to squash the two commits of this PR.

**Pull request merged**
