### PR TITLE
Split end2end profile testcases & cache objects for reuse

### PR DESCRIPTION
**Pull request by andy-maier**
For details, see the commit message.

Testing: `make end2end` against the smigood group. Please compare the total execution time to before the change.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
andy/end2end-split-tests

===== 177 failed, 725 passed, 684 skipped, 160 warnings in 5027.45 seconds =====
/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
make: *** [end2end] Error 1

real	83m50.457s
user	6m23.433s
sys	0m5.242s

We cannot effectively measure since the number of tests has changed as part of the pr. 

The master branch from which this was derived defines:

collected 1339 items for the test wheras this branch defines 1586 items

**Test against current master**

The overall time for this test was:

==================Current master
-- Docs: https://docs.pytest.org/en/latest/warnings.html
====== 4 failed, 651 passed, 684 skipped, 135 warnings in 5666.21 seconds ======
/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
make: *** [end2end] Error 1

real	94m29.260s
user	5m36.176s
sys	0m5.799s

There was some speed gain but it  is difficult to tell since the number of tests executed was different.

Copied details from master branch to shared pywbem but goofed up the branch and redoing it.

**Comment by andy-maier** [comment]
The number if tests changed because the tests are now split into smaller portions, but the overall test workload should not have changed, unless thde number of online servers changed. However, closer analysis is needed. Please upload the logs.

**Comment by andy-maier** [comment]
Here is the analysis of the number of testcases on the two end2end runs on master and on this PR:

Result: Both runs ran against 13 servers, not 12. The number of testcases for each test file is as expected, based on the changes in this PR. See the calculations below.

Run on master:
```
collected 1339 items

test_profile_generic.py 1014 (= #prof(78) * #srv(13)) -> ok
ss.....ss...ssssss..sss..s.s..ssssssssss..sssss..sssss....s...ssssssss..s.....
sss.ssssss..............ssssss.................sss.s..sssssssssssss....sss.s..
sssss..s..sss....s..s...ss..ss.......ss...........ss..........sss...........ss
ss.....ssssss..s........ssss.......ssss...s.......sssss........ssssssssss.ssss
ssssssssssssssssssssssss..sssssssssss..sssssssssss..sssssssssss..ss..sss.sss..
sssssssssss......sss......sssssssss...................sssssssssssss..sss.sss..
sssssssssss..sssssssssss..sssssssssss......ssss..s..ss..sssssss..sssssssssss..
..ssssss..s..sssssssssss..sssssssssss..ssssssssssssssss.ssss..sssssssssss..sss
ssssssss..sssss..ssss..sssssssssss..ssssssssss...ssssss.ssss..ssssssssssss..ss
ssssssss..sss....sss....ssssssssss..sssssssssss..sssss..ssss..ssssssssssss.sss
ssssssss.sssssssssssss.ssssss.sssssssssssssssss..ssssss........ss..sssss.sssss
..sssss.sssss..sssss.sssssss..sssssssssssssssss.sssssss.ssssssssssssssss.sssss
..sssss.sssss..ssssssss.....sssss.sssssssssssssss.sssssssssssssssss..sssssssss
test_profile_snia_server.py 13 (= #srv)
F
F
.
F
.
F
.
.
.
.
.
.
.
test_server.py 312 (= #defns(4) * #tc(6) * #srv(13)) -> ok
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
```
Run on this PR:
```
collected 1586 items

test_profile_generic.py 1014 (= #prof(78) * #srv(13)) -> ok
ss.....ss...ssssss..sss..s.s..ssssssssss..sssss..sssss....s...ssssssss..s.....
sss.ssssss..............ssssss.................sss.s..sssssssssssss....sss.s..
sssss..s..sss....s..s...ss..ss.......ss...........ss..........sss...........ss
ss.....ssssss..s........ssss.......ssss...s.......sssss........ssssssssss.ssss
ssssssssssssssssssssssss..sssssssssss..sssssssssss..sssssssssss..ss..sss.sss..
sssssssssss......sss......sssssssss...................sssssssssssss..sss.sss..
sssssssssss..sssssssssss..sssssssssss......ssss..s..ss..sssssss..sssssssssss..
..ssssss..s..sssssssssss..sssssssssss..ssssssssssssssss.ssss..sssssssssss..sss
ssssssss..sssss..ssss..sssssssssss..ssssssssss...ssssss.ssss..ssssssssssss..ss
ssssssss..sss....sss....ssssssssss..sssssssssss..sssss..ssss..ssssssssssss.sss
ssssssss.sssssssssssss.ssssss.sssssssssssssssss..ssssss........ss..sssss.sssss
..sssss.sssss..sssss.sssssss..sssssssssssssssss.sssssss.ssssssssssssssss.sssss
..sssss.sssss..ssssssss.....sssss.sssssssssssssss.sssssssssssssssss..sssssssss
test_profile_snia_server.py 260 (= #tc(2 + 3 * 6) * #srv(13)) -> ok
..FFFFFF..FFFFFFFFF.
.......FFFFFFFFFFFF.
F....F....FFFFFFFFFF
FFFFF.........F....F
FFFFFFFFFFFFFFFFF.F.
...F.....F....FFFFFF
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
FFFFFFFFFFFFFFF.....
test_server.py 312 (= #defns(4) * #tc(6) * #srv(13)) -> ok
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
```

**Comment by andy-maier** [comment]
Here is the analysis of the failed testcases on the two end2end runs on master and on this PR:

On master:
  - Brocade: 1 ParseError on empty TYPE
  - Brocade1: 1 ParseError on empty TYPE
  - EMC1: 1 AssertionError on invalid property value ECOM_OtherCommunicationMechanism.CommunicationMechanism
  - EMC4: 1 assertion error on invalid number of associated instances

On PR:
  - Brocade: 12 ParseError on empty TYPE with a1..a4 (References / ReferenceNames) -> consistent
  - Brocade: 3 ParseError on empty TYPE with a6 -> inconsistent, investigate:
    Test_SNIA_Server_Profile.test_Namespace[assert_association_a6-server_definition=Brocade]
    Test_SNIA_Server_Profile.test_System[assert_association_a6-server_definition=Brocade]
    Test_SNIA_Server_Profile.test_ObjectManagerCommunicationMechanism[assert_association_a6-server_definition=Brocade]
  - Brocade: 1 CIMError instance not found: inconsistent, investigate:
    Test_SNIA_Server_Profile.test_System[assert_association_a5-server_definition=Brocade]
  - Brocade1: 12 ParseError on empty TYPE with a1..a4 (References / ReferenceNames) -> consistent
  - Brocade1: 3 ParseError on empty TYPE with a6 -> inconsistent, investigate:
    Test_SNIA_Server_Profile.test_Namespace[assert_association_a6-server_definition=Brocade1]
    Test_SNIA_Server_Profile.test_System[assert_association_a6-server_definition=Brocade1]
    Test_SNIA_Server_Profile.test_ObjectManagerCommunicationMechanism[assert_association_a6-server_definition=Brocade1]
  - Brocade1: 1 CIMError instance not found: inconsistent, investigate:
    Test_SNIA_Server_Profile.test_System[assert_association_a5-server_definition=Brocade1]
  - EMC1: 4 AssertionError on invalid property value ECOM_OtherCommunicationMechanism.CommunicationMechanism -> consistent
  - EMC4: 2 assertion error on invalid number of associated instances -> consistent
  - All servers: KeyError on missing cache list -> new, investigate.

**Comment by andy-maier** [comment]
I could not reproduce the KeyError locally with two servers. I suspect this has to do with the order in which the testcases are executed. association approach a1 stores its results in the cache, and association approaches a2 to a6 access that, so there is an order dependency now between different testcases. Pytest normally executes the testcases in order of appearance in the source file, so that should work (in theory). However it does not. I have added debug code and the verbose option of pytest in an update of this PR.

@KSchopmeyer Can you please re-run the end2end test just with this PR and post the log file? I believe the number of servers can be reduced to 4 or so, to speed it up.

**Comment by andy-maier** [comment]
@KSchopmeyer Karl, the last update to this PR fixes the KeyError (I hope). It passes the end2end test on my local virtual server as before, but then I could not reproduce the KeyError there either.

Could you please run the end2end test of just this PR on all 13 smigood servers and post the log?

**Comment by andy-maier** [comment]
end2end test against a smaller group of SMI testlab servers showed 22 errors, all of which are considered server implementation errors. Merging.

**Pull request merged**
