### PR TITLE
Pylintfixes4 misc fixes to reduce pylint count

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Number of mostly cleanup including adding some docstrings, rename some variables, bunch of
disables, etc.  Did some changes to the testsuite also primarily multiple line alignment.

Passed tests locally.  Note that count is down to 599 and I added at least 10 new TODOs

Summary with this change is as follows:
 Count of messages per module summary
======================================
pywbem.mof_compiler                240
test_nocasedict                     44
pywbem.cim_obj                      33
test_cim_obj                        32
pywbem.tupleparse                   32
pywbem.cim_xml                      29
test_mof_compiler                   29
test_cim_xml                        27
test_cimxmlparse                    24
test_client                         22
pywbem.cimxml_parse                 21
pywbem.cim_http                     17
test_tupleparse                     15
pywbem.cim_operations               12
os_setup                            11
setup                                5
pywbem.wbemcli                       2
pywbem.tupletree                     1
test_cim_http                        1
                                     0
======================================

Count by message type
Message Type                 Msg Count
======================================
(missing-docstring)                146
(using-constant-test)                2
(broad-except)                       2
(dangerous-default-value)           33
(bad-builtin)                       10
(undefined-variable)                 3
(attribute-defined-outside-init)       4
(cell-var-from-loop)                 1
(unused-import)                      9
(unused-argument)                   11
(deprecated-lambda)                  9
(redefined-variable-type)            8
(redefined-builtin)                  6
(unused-variable)                    8
(not-an-iterable)                    1
(cyclic-import)                      1
(fixme)                             86
(no-self-use)                       27
(no-member)                         14
(unnecessary-lambda)                 2
(bad-continuation)                  11
(bad-inline-option)                  4
(line-too-long)                      2
(protected-access)                   5
(invalid-name)                     194
======================================
Total                              599

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
the set of files changes is:
cim_obj
cim_operations
cim-xml
cimxml-parse
tupleparse
tupletree
test_cim_xml
test_client
test_tupleparse

**Comment by KSchopmeyer** [comment]
+1

**Comment by KSchopmeyer** [comment]
Karl voted yes.

**Comment by andy-maier** [comment]
+1

**Pull request merged**
