### PR TITLE
Issue #616: Fixed double CreateInstance in _create_subscription() and __enter__() return value.

### PR DESCRIPTION
**Pull request by andy-maier**
This PR fixes items 3 and 4 in issue #616.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
We did the same things. See my pr 619.  I also fixed a bunch of things in run_cimoperations.py that changed with the latest subscription mgr updates

**Comment by KSchopmeyer** [comment]
+1, Now we need to bring this and 619 together.

**Comment by andy-maier** [comment]
After merging PR #619, the only remainders in this PR are some style improvements (setting namespace in CIMInstanceName objects as part of the Constructor, instead of updating the instance attribute afterwards).

**Pull request merged**
