### PR TITLE
Upgraded wbemcli script to 0.9 level of code, in support of certificates

### PR DESCRIPTION
**Pull request by andy-maier**
Addresses issue #308.
Ready to be merged into 0.8.

Please review and test.

### CODE REVIEW

**Comment by andy-maier** [comment]
Rebased on stable_0.8 to resolve a merge conflict in the NEWS file.

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
Not sure what yet but we did something nasty.  Did a simple wbemcli with this and got the following:

Not even trying to send to the server:


>>> y = gc('CIM_ManagedElement')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/wbemcli.py", line 623, in GetClass
    PropertyList=pl)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 1587, in GetClass
    **params)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 564, in imethodcall
    for x in params.items()]
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 2596, in tocimxml
    (value, builtin_type(value)))
ValueError: Can't convert None (<type 'NoneType'>) to CIM XML

Seems to be consistent.  It is apparently when wbemcli is trying to get qualifierdecls.  It occurs on a number of the class operations (ec, gc).

**Comment by andy-maier** [comment]
Karl, This is due to the 0.9 wbemcli now having None as default args, which requires a check for that in imethodcall, which did not get merged.

I addition, i discovered that the ec() function of wbemcli calls ECN of cim_ops. Need to check whether this issue is also in other branches.

Both is fixed in the last commit to this branch.

**Comment by KSchopmeyer** [comment]
+1

Tested bunch of things on wbemcli and the seem to work both python 3 and 2

**Pull request merged**
