### PR TITLE
Fixes #1355: Issues with case insensitivity on classnames in pywbem_mock

### LINKED ISSUE #1355: Enumeration operations in mock support treat class names case sensitively
The fake enumeration operations in the pywbem mock support create a listof subclass names via `_get_class_list_enums()` and then check the desired classname using the `in` operator, which is case sensitive. This makes the whole classname comparisoin case sensitive in the operations.

The issue exists (at least) in the following `FakedWBEMConnection` methods:

* `_fake_enumerateinstances()`
* `_fake_enumerateinstancenames()`
* `_fake_enumerateclasses()`
* `_fake_enumerateclassnames()`

and probably also in the association operations, e.g. for those filter arguments that are class names, or for the class-level invocations.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Ready for review

See commit messages for details.  

Note: The changes to the mocker code are minor. The changes to the tests are more significant in that  this adds a significant number of tests and it was easier to rewrite some of the tests rather than to continue to extend them directly.

NOTE: We also cleaned up one issue where we had been using strings to define CIM_ERR... messages in the tests and changed all of that to use the status_code variables directly.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
We are having problems with python 2 now:

  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 259, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e))
pluggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (coverage 4.0.3 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('coverage>=4.4'))!
make: *** [test] Error 1

**Comment by andy-maier** [comment]
Karl, I tried to roll this one back to 0.12.6, but this is not as easy as I thought. A purely mechanical cherry-pick resulted in several inconcistencies (not even flake8 would get over that). I suggest that you perform the rollback, since you know that code better.

**Comment by KSchopmeyer** [comment]
**QUESTION:**
Rebased but the rebase added 3 extra lines to PKG_INFO that are not in master:

Project-URL: Bug Tracker, https://github.com/pywbem/pywbem/issues
Project-URL: Documentation, https://pywbem.readthedocs.io/en/latest/
Project-URL: Source Code, https://github.com/pywbem/pywbem

Bothers me that these things just sort of slide in.

**Comment by andy-maier** [comment]
They only were sliding into this PR because you have updated the PKG-INFO file in this PR.
These lines create additional links on Pypi and have been added explicitly by PR #1363.

**Comment by andy-maier** [comment]
PR #1377 has rolled the fix back into 0.12.6.

**Pull request merged**
