### PR TITLE
Fixes #832, #26: Use pbr+req files; Add min/max pkg levels; Fix OS-X runs; Other improvements

### LINKED ISSUE #832: Migrate pywbem setup to using pbr & requirements files
Any user of pywbem currently has the problem on Windows that is described in pywbem/pywbemtools#78.

The best solution to this is to migrate pywbem setup to using pbr & requirements files, and to throw away `os_setup.py` and to use `pywbem_os_setup.sh` instead. Also requires docs updates.

### PR DESCRIPTION
**Pull request by andy-maier**
Ready for review and merge. For details, see commit message.

Sorry for accumulating a number of things in this PR, but they were all related. I have split out some changes that ended up being unrelated, into separate PRs (#861 and #862). The commit message of this PR here has carefully been edited to reflect all changes. So one way of simplifying the review would be to review the changes as described by the comment message and to go to the actual file changes only very partially.

The Travis CI runs for OS-X have been disabled again in this PR in order to keep the CI runs quick for PRs; the OS-X runs can be seen in PR #791 which has been rebased on this PR and has OS-X enabled.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
I like it. This is going ot make life easier.

Tried installing into virtual env

 Hit an error in first 'make all'

  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/typing-3.6.1-py2.7.egg'
make: *** [develop] Error 1

Hit another error when i did make build and then make install. wanted to install into os level dirs despite fact that I am in virtual env.

Installing runtime requirements with PACKAGE_LEVEL=latest
rm -Rf build pywbem.egg-info .eggs
sh -c "./pywbem_os_setup.sh"
Installing OS-level prerequisite packages on platform Linux (distro: ubuntu, family: debian)...

**Comment by andy-maier** [comment]
For now, the order of make targets needs to be correct.

In a freshly created virtualenv, the prerequisite make targets are always:
    `make install develop` - targets in exactly this order

On top of that, you can then do:
    `make test check build builddoc` - targets in any order

It is true that `make all` does not do that right, at the moment.

**Comment by andy-maier** [comment]
Karl, this PR is now ready as far as I'm concerned. Could you please double check on the error you saw?

**Comment by andy-maier** [comment]
Karl, this PR is now ready.
Please review it again and double check the error you saw.

**Comment by andy-maier** [comment]
@KSchopmeyer Karl, this PR is now ready for re-review. Read the original comment at the top of the PR for details.

**Comment by KSchopmeyer** [comment]
Karl agrees. Lets check this in

**Pull request merged**
