### PR TITLE
Fixes #958: Clean up mock. Part 1, display_repo

### LINKED ISSUE #958: Remaining work in pywbem mock support
* Review the message text of exceptions that are being raised.
* Consolidate the text in the .rts file, in the sections after "Overview".  DISCUSS EXAMPLES
* Verify the statements about prerequisites and non-prerequisites for adding CIM objects in the Overview section in the .rst file. Also, consider mentioning that lite mode exists, at that point. Are these statements valid for the setup methods, or for the operations, or both?
* Resolve the TODOs in code and testcases that are not marked future.
* In display_repository():
  - The `==Repository==` line and its corresponding end line surround each single namespace, and not the entire repo as suggested by their text. Either change text in these lines, or produce them only once for the entire repo.
  - In the MOF format, the non-MOF lines (e.g. "==...", "Namespace root/cimv2: contains ...", or "Path=...") could become MOF comment lines, then the entire output can be used again as MOF.
  - In the MOF format, the first class in a namespace listing could be preceded by an empty line.
  - In the XML format, the non-MOF lines could become XML comment lines (`<!-- ... -->`), but I feel that is less important than for MOF (and also a bit ugly).
  - In the XML format, the CIM-XML could be pretty-printed.
  - In the XML format, the objects in a namespace listing could be separated by empty lines.
  - In the REPR format, the classes in a namespace listing could be separated by empty lines.
  - In the XML and MOF formats, the output of the path could use the new `to_wbem_uri()` method to make it more explicit that we want a WBEM URI.
  AGREED: Really good idea.
  - For classes and qualifier decls and namespaces, the output should be sorted by name, and a TODO should be added that in the future, we should preserve order.
   AGREED. KS.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Ready for review and merge.

Fixes the issues with the display_repo documented in issue #958

### CODE REVIEW

**Comment by andy-maier** [comment]
Karl wants to make another small change on this one (similar to the other mock PR?) -> setting update needed.

**Comment by andy-maier** [comment]
Karl, I will resolve the merge conflicts later today and will merge it.

**Comment by andy-maier** [comment]
Hi Karl, I thought this would be an easy conflict resolution, but it wasn't. After rebasing it on master and resolving a conflict, the test failed (commit 508a229). I fixed that (changed two occurrences of `subscribe_method()` to the renamed `add_method_callback()`), in commit 17c3669.

However, I started wondering why this part of the changes is even in this PR which is about display of the repository.

So, could you please double check that this PR contains what you want it to contain? I have set "discussion needed" on this one.

**Comment by KSchopmeyer** [comment]
I really messed this one up somehow.  Will clean up tonight.  Actually, I will create new branch with just my code based on master and eliminate some of the confusion. 

Thanks for catching.  Off to western New Mexico today and San Jose tomorrow

**Comment by andy-maier** [comment]
Safe travels, Karl!

**Comment by KSchopmeyer** [comment]
I am closing this PR and replacing it with pr #999. That pr contains the same code for the display and changes to the doc but not the extra that accidently got in.

**Pull request closed without merging**
