### PR TITLE
Cleaned up change log.

### PR DESCRIPTION
**Pull request by andy-maier**
Some items have been merged (e.g. items for indication support).
Cleaned up formatting.
Moved a few items between Enhancements and Bug fixes.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
9, Line 86 - Add

**1. Line 89**, WBEMServer class is treated as an afterthought of indications.  I think that it should appear in the description as the equal of the indications functionality.  Turns out that this is the one a bunch of users really wanted.

For example consider the following proposal"

* Implemented support for reading information from the DMTF WBEM Server and RegisteredProfile classes with a new `WBEMServer` class:

  - The `WBEMServer` class, provides consistent and convenient access to the common
    elements of the WBEM Sersver Profile, including namespaces names, interop
    namespace name, registered profile information, server branding, and central/scoping class
    algorithms.

  - Added unit tests for this new class in  `run_cim_operations.py` and testclient

  - Added a demo of the discovery abilities of the `WBEMServer` class in
    the `examples/explore.py` script.

  **Experimental** - This new class is experimental for pywbem version
  0.9.0 because this is the initial release of a significant change and subject
  to changes to the API.

(issues # 9, #346)

* Implemented support for WBEM subscription management and the WBEM Indication listener:

  - Added a `WBEMListener` class that allows the creation of a listener entity
    to receive indications. 

  - Added a `WBEMSubscriptionManager` class that allows management of
    indication subscriptions, filters, and destination instances on the WBEM Server using the new
   WBEMServer class.

  - Added unit tests for these new classes and extended other existing tests
    accordingly, e.g. `run_cim_operations.py`.

  **Experimental** - These new classes are experimental for pywbem version
  0.9.0 because this is the initial release of a significant change and subject
  to changes to the API.

**2. line 116**:  Is the windows installable tested at all.  It is not tested by me at this point? If not should we note this?

**3. line 160** - Added new status codes 20 - 28.  Add comment "specifically to support the pull operations"

**4. Line238** Extended live testing with `cim_operation.py` to include tests on the
+  `WBEMServer` class (Issue #346)  Remove this since covered above.

**5. Line233** - This should probably be part of the section on indications in line

**6. line 238** - Extended live testing with `cim_operation.py` to include tests on the
  `WBEMServer` class (Issue #346)

   This is already in the WBEMServer description above except for the issue #468 


**7. Line 345** - I see no mention of the fact that we cleaned up the timeouts on ssl. (issue 363, 364). Note that we also created a specific test for timeouts against a live server.


. . .

**Comment by andy-maier** [comment]
Karl, I have addressed most of your comments in commit 000c926.

See the **DISCUSSION POINTS** in your comment, above.

**Comment by KSchopmeyer** [comment]
Looks good to me. +1

**Comment by andy-maier** [comment]
I also prefer removing it.

I will merge this PR and create a separate one for the removal.

**Pull request merged**
