### PR TITLE
 Fixed issues in SSL support for Python 3.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
This is currently untested since all tests fail in hotel once you use ip address.  Think they are blocking everything.

Even if it passes, it is not tested

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Note that I have not been able to test this one because of issues here in hotel.  Will test when I get to plugfest.

**Comment by andy-maier** [comment]
You need to be careful with inheriting from object when the rest of the tree does not.

**Comment by KSchopmeyer** [comment]
I agree. That was really just a test to see about removing some pylint disables.  Of course, passing the tests means nothing since this change is not really tested.  Get a chance to test against a number of real servers today.

**Comment by andy-maier** [comment]
This also needs to go into 0.8.3.

**Comment by KSchopmeyer** [comment]
Commited working update but python 3 still broken.

**Comment by KSchopmeyer** [comment]
With the changes in the pr update of 30 april, we can now communicate with an ssl host successfully.  However, we have not tested with valid certificates yet (tested with N0-verification) and we have to add one more piece of code to validate the hostname when validation is true.  Since that is not in all versions of the ssl python 3 library we will have to de it externally.  Other than that, the only additonal thing is to test against a host where us and the host have certificates with a common ca.

**Comment by andy-maier** [comment]
This PR fixes issue #274 (and issue #150 once we roll it back to v0.8.3).

**Comment by KSchopmeyer** [comment]
At this point the code allows https connections with python3 with -no-verification.  I am having problems with the verification phase simply because of trying to get certs to match.

Isuggest that we bypass the check_hostname feature for this patch unless it is built(in python3 theey gradually added parts of the check_hostname feature bewteen 3.2 and 3.5 so we would either have to do the backport path or live with whatever the python release offers.

**Comment by andy-maier** [comment]
In Python 3, we only support 3.4 and upwards. So let's figure out what is in 3.4 out of what we need.

Is the check_hostname feature verifying the hostname stated in the server certificate against the hostname the client used to connect to the server?

**Comment by KSchopmeyer** [comment]
Python 3 only:We still have issues with the match-hostname in that different versions of python ssl module offer different levels of support for this concept.  See the following site:

https://pypi.python.org/pypi/backports.ssl_match_hostname

The question is whether we try to maximimze security by insuring that this function works.

**Comment by KSchopmeyer** [comment]
We agreed that we can live with the limitations on the match_hostname between python 3.4 and 3.5. But we need to document them.

Karl needs to complete the test to confirm that the verifcation works with the known limitations on 2.4 adn 3.5.
We also need to add an installation check to assure that pywbem is being installed on 3.4 or 3.5.

**Comment by andy-maier** [comment]
On match_hostname and the backports module:

If I understand this correctly, then Python 3.4 and 3.5 have everything we need ot of the box, and the backports module is not needed. If we want to have hostname matching for Python 2.6 and 2.7, we need the backports module.

Correct?

If so, I suggest that we use the backports module for 2.6 and 2.7.

**Comment by andy-maier** [comment]
Do you want to cherry-pick the change from #293 into this PR?

    git cherry-pick <short-commit-id>

**Comment by KSchopmeyer** [comment]
For python 2.7, no.  Not sure how but the trace I showed you displayed m2Crypto doing the match_hostname.

Lets commit 293 and its corresponding 0.8.4 and then do this one and its corresponding 0.8.4.  I have not prepared the 0.8.4 version but will tonight.

More straight forward that cherry-pick.  Actually I just merged them to do the test.

**Comment by andy-maier** [comment]
Karl,
I have merged PR #293 and its coresponding 0.8 PR #290.

Please rebase this PR here on master to get it.

**Comment by KSchopmeyer** [comment]
Integrated with pr 289, index error on exception. Note that I made one other change that I marked for discussion, changed the  SSL context setup from sslv23 to the function create_default_context(). This appears to be the general recomendation since it sets up what is best default between ssl module and openssl.  However, that is not as well tested as the remainder.
DISCUSSION: keep this change or revert.

**Comment by KSchopmeyer** [comment]
+1 except for the discussion items above.

**Comment by KSchopmeyer** [comment]
issue of default_context.  Andy proposes that we set a minimum level TLS as TLS1.0 and that becomes the standard.  We will do another isssue for this.

We will review the tunnel question as a separate issue.

**Comment by andy-maier** [comment]
We agreed in the call today to merge this one.

**Pull request merged**
