### PR TITLE
Move CIMProperty.tomof processing for classes to CIMProperty class. #231 #223 #35

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Move class  property tomof processing from CIMClass to CIMProperty. #231
Add processing of values to CIMClass.property processing.  This was completely ignored which resulted in about 100 issues in trying to recompile the schema mof.  This code already existed in 
CIMProperty.tomof() - Issue #223 

Add code to keep qualifier.tomof lines under 80 char long. Corrected error use of :term in doc issue -#35

Review but I need to update to add change log update for this change.
NOTE: We will not really know how this works until I finish commit the round-trip code and we can test
against the whole dmtf schema.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
+1 Please review.

**Comment by andy-maier** [comment]
-1

I found only some nits:
* The `bool` type can be specified directly as a parameter type and does not need `:class:'py:bool'`. This applies to `CIMProperty._array_val2mof()` and `CIMProperty.tomof()`.
* The new `isInstance` parameter of `CIMProperty.tomof()` does not follow the convention we use othwerise. Suggest to name it `is_instance`.

**Comment by KSchopmeyer** [comment]
I agree with second but could you clarify first comment.

**Comment by andy-maier** [comment]
On my first comment:

The confusing part may have been that I used straight quotes, which I did only because I don't know of a markup syntax in these comments here that allows to show a backquote in monospaced font (However, I just found out that in an indented example section, that is possible).

Anyway, here is an explanation:

In order to reference a built-in type from anywhere in a docstring, the explicit syntax you used is necessary. 

However, in the type portion of a parameter description, the short form using just the type names is sufficient (the type definitions are then search automatically). The explicit form works as well, though.

I am suggesting to use the short form because it is simpler and because it is already used in many places.

Example parameter docstring using the short form:

    folded (bool):
      Some description

The same parameter docstring using the explicit form:

    folded (:class:`py:bool`):
      Some description

Both generate the same link.

**Comment by KSchopmeyer** [comment]
got it.  The sphinx rule set is complex

**Comment by andy-maier** [comment]
+1

**Pull request merged**
