### PR TITLE
Fixes #219: 0.8.2 install failure on Windows

### LINKED ISSUE #219: Fail to install pywbem-0.8.2 on Windows
On Windows, installing **pywbem-0.8.2** from pypi fails due to **m2crypto** compiling issue.

### PR DESCRIPTION
**Pull request by andy-maier**
This PR contains debug code to analyze issue #219.

To try this out, download and unpack the [pywbem distribution archive](https://github.com/pywbem/pywbem/blob/fix_issue_219/dist/pywbem-0.8/pywbem-0.8.3.dev0.tar.gz), and install from there, using:

    python setup.py install

### CODE REVIEW

**Comment by andy-maier** [comment]
The PR now solves the original problem.

Ready to be merged. Please review.

**Comment by KSchopmeyer** [comment]
Since I have been ignoring windows for a while, I need to recreate my windows python env. Will review today.

**Comment by KSchopmeyer** [comment]
now I know why I was ignoring windows.  With 2.7.11 I get the following errors trying to use make but I am not sure how much of this we want to sort out, etc.  Using windows 7 up-to-date.

====================
make test
Lots of errors but I lost the output and now just does:

(pywbem27) C:\Users\kschopmeyer\python\pywbem>make test
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
  File "<string>", line 1
    import sys; sys.stdout.write('sys.version_info[0])
                                                     ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'str' object is not callable
'test done; results are in test_.log'
===================================================================
make clobber:

(pywbem27) C:\Users\kschopmeyer\python\pywbem>make clobber
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
'sh' is not recognized as an internal or external command,
operable program or batch file.
  File "<string>", line 1
    import sys; sys.stdout.write('sys.version_info[0])
                                                     ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'str' object is not callable
find . -name "*.pyc" -delete
Access denied - .
File not found - -NAME
File not found - -DELETE
make: *** [clean] Error 1

=================================================================
make develop

Using c:\users\kschopmeyer\envs\pywbem27\lib\site-packages\six-1.10.0-py2.7.egg
Finished processing dependencies for pywbem==0.8.3.dev0
develop: Installing prerequisite Python packages
Processing Python package requirement: pytest>=2.4
Installed Python package version is sufficient: pytest 2.9.1
Processing Python package requirement: pytest-cov
Installed Python package version is sufficient: pytest-cov 2.2.1
Processing Python package requirement: epydoc==3.0.1
Installed Python package version is sufficient: epydoc 3.0.1
Patching Epydoc
Epydoc patch directory: C:\Users\kschopmeyer\Envs\pywbem27\lib\site-packages\epy
doc/epydoc-3.0.1-patches
Downloading Epydoc patches into patch directory: C:\Users\kschopmeyer\Envs\pywbe
m27\lib\site-packages\epydoc/epydoc-3.0.1-patches
mkdir: cannot create directory `C:': File exists

error: mkdir returns rc=1: mkdir: cannot create directory `C:': File exists
make: *** [develop] Error 1

================================================
make install

**Comment by andy-maier** [comment]
For the development environment, one needs CygWin or something similar. You can then run `make` either in the windows command processor, or in the cygwin bash shell.

A user of pywbem does not need CygWin or similar. You can verify that by running `python setup.py install` (or any other command, see its `--help-commands` option) in the Windows command processor, without CygWin in the PATH.

**Comment by KSchopmeyer** [comment]
Will fight out the cygwin issues later. It can be a real pia.  In any case, I now gets through the setup without an error and runs some simple tests.

I will go

+1

on this one since it fixes a specific problem, but I am not comfortable with windows and pywbem until I get through the whole develop, setup, run, etc. with cygwin.  Even getting virtualenv is a pia with windows/cygwin.

**Pull request merged**
