### PR TITLE
Fixes #351: Operation recorder, final part

### LINKED ISSUE #351: Generate test_client yaml from within the WBEMConnection operation methods
In order to produce more test_client yaml testcases, it would be beneficial to generate those, instead of making them up manually. This can be achieved by having code in the WBEMConnection class in `imethodcall()` and `methodcall()` at the end when the result is available, that emits the yaml testcase for this operation. At this point, everything is available: Python input and output, and CIM-XML request and response (via debug). This could be controlled by another WBEMConnection instance attribute.

### PR DESCRIPTION
**Pull request by andy-maier**
Ready to be merged.
Please review. Reviewed latest and have comments below.  It does go through an example and run_cim_operations.py but with some errors (see below).

Final step for test_client yaml generation with the `TestClientRecorder`.

Known limitations:
- The CIM-XML in the request and response payload is not pretty-printed in the yaml.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
We have a bug somewhere.   When I turned on the recorder with the enumerateinstances.py example I got:

Usage: ./enuminstances.py server_url username password namespace'               ' classname
Using internal defaults
Requesting url=http://localhost, ns=root/cimv2, class=CIM_ComputerSystem
Traceback (most recent call last):
  File "./enuminstances.py", line 107, in <module>
    sys.exit(main())
  File "./enuminstances.py", line 102, in main
    execute_request(server_url, creds, namespace, classname)
  File "./enuminstances.py", line 58, in execute_request
    INSTANCES = CONN.EnumerateInstances(classname)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 1442, in EnumerateInstances
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 280, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 359, in record
    tc_pywbem_response['result'] = self.toyaml(pywbem_result.ret)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 418, in toyaml
    ret.append(self.toyaml(item))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 439, in toyaml
    ret['properties'] = self.toyaml(obj.properties)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 425, in toyaml
    ret[key] = self.toyaml(obj[key])
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 469, in toyaml
    ret['value'] = self.toyaml(obj.value)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 526, in toyaml
    raise TypeError("Invalid type: %s" % type(obj))
TypeError: Invalid type: <class 'pywbem.cim_types.Uint16'>


Have not dug into the code any further yet.

**Comment by andy-maier** [comment]
Strange that the type is not shown in the exception message... Need to reproduce...

**Comment by KSchopmeyer** [comment]
I know I put this note in this morning but must have forgotten to save.  I replace the exception raise with a print of the exception and got the following

Requesting url=http://localhost, ns=root/cimv2, class=CIM_ComputerSystem
TypeError. invalid type: <class 'pywbem.cim_types.Uint16'>
TypeError. invalid type: <class 'pywbem.cim_types.Uint16'>
TypeError. invalid type: <class 'pywbem.cim_types.Uint16'>

**Comment by andy-maier** [comment]
Commit cbdcdc9 fixes the issue Karl discovered.

The generated test YAML is now ready to be used as a test_client testcase, except when exceptions occur, in which case the right callback function needs to be specified manually (everything else should be readily useable as generated).

**Comment by KSchopmeyer** [comment]
It writes the file at least for enuminstance.py. 

Note that all xml is doublespaced for some reason:

     cimoperation: MethodResponse
    data: '<?xml version="1.0" encoding="utf-8" ?>

      <CIM CIMVERSION="2.0" DTDVERSION="2.0">

      <MESSAGE ID="1001" PROTOCOLVERSION="1.0">

      <SIMPLERSP>

      <IMETHODRESPONSE NAME="EnumerateInstances">

      <IRETURNVALUE>

      <VALUE.NAMEDINSTANCE>

      <INSTANCENAME CLASSNAME="PG_ComputerSystem">


Ran against run_cim_operations.py.  Gets some errors.  

1.  _recorder line 522.    File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.9.0.dev0-py2.7.egg/pywbem/_recorder.py", line 522, in toyaml
    ret['methodname'] = self.toyaml(obj.methodname)
AttributeError: 'CIMMethod' object has no attribute 'methodname'

Think the internal arg name is name.  That was an issue in any case since param and internal name are different.

2.

ERROR: test_all (__main__.InvokeMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_cim_operations.py", line 1650, in test_all
    Ref=name)
  File "./run_cim_operations.py", line 99, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.9.0.dev0-py2.7.egg/pywbem/cim_operations.py", line 4595, in InvokeMethod
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.9.0.dev0-py2.7.egg/pywbem/_recorder.py", line 292, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.9.0.dev0-py2.7.egg/pywbem/_recorder.py", line 382, in record
    tc_operation[arg_name] = self.toyaml(pywbem_args.args[arg_name])
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.9.0.dev0-py2.7.egg/pywbem/_recorder.py", line 567, in toyaml
    "%s %s" % (obj.__class__.__name__, type(obj)))
TypeError: Invalid type in TestClientRecorder.toyaml(): timedelta <type 'datetime.timedelta'>


It made it alll the way through run_cim_operations.py with 11 errors, 3 failures.

Maybe with these simple changes we commit this and fix anything else after committed. 

Note: it is VERY slow so don't plan to run against the world with this.  Took about 5 min to run a single test.

**Comment by andy-maier** [comment]
Sorry for not testing better.

The element name in any CIM objects is `classname` in case of class related elements, and `name` in all other cases, except for CIMMethod where the instance attribute is documented as `methodname` but is actually `name`, and the ctor arg is both documented and actually `methodname`. That has been the case already in 0.7.0.

Both the instance attribute and the ctor arg are part of the external interface of the class.

**Proposal** for a compatible change to get this consistent:

* Rename the `methodname` argument of the ctor to `name`, and add an optional `methodname` argument that when supplied causes a DeprecationWarning to be issued. This is a compatible change because in Python, the caller must put the positional args first, before specifying named args, and it works because we change the first argument.

        def __init__(self, name, return_type=None, parameters=None,
                 class_origin=None, propagated=False, qualifiers=None, methodname=None):
            if methodname is not None:
                warnings.warn("The methodname parameter of CIMMethod is deprecated",
                               DeprecationWarning)
            self.name = name
            . . .

    All of these work:

        CIMMethod('Stop', str)                           # old and new usage
        CIMMethod('Stop', return_type=str)               # old and new usage
        CIMMethod(name='Stop', return_type=str)          # new usage
        CIMMethod(methodname='Stop', return_type=str)    # old usage

* Fix the documentation of ctor and instance attribute to say `name`.

**Comment by andy-maier** [comment]
**On issue 1:**

I know, but this is how it is returned from OP, and prettifying the CIM-XML is not implemented yet.

**On issue 3:**

Will be fixed.

**Comment by andy-maier** [comment]
Commit 946ae38 addresses issues 2 and 3.
I suggest to ignore issue 1 for now.

**Comment by andy-maier** [comment]
It now seems to pass run_cim_operations.py (I stopped the long run and the short tun after 30min each), and it passes a locally modified examples/explore.py that used the recorder.
+1

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
