### PR TITLE
Added response_performance.sh script

### PR DESCRIPTION
**Pull request by andy-maier**
**Note: This PR is on top of PR #1658, so review only the delta (last commit)**
For details, see the commit message.

### CODE REVIEW

**Comment by andy-maier** [comment]
Updated the script accordingly.

I'm against doing that in run_response_performance.py: It would require adding the ability to have multiple runs, sothere can be a consistent run-ID on each log file. Also, unless we introduce a config file as input, changing the parameters would require editing the Python script. I think separating that out in a shell script makes it clear that that is just a convenience, and the interface to run_response_performance.py is the real interface.

**Comment by KSchopmeyer** [comment]
DISCUSSION: I added an option log to the performance script and now it probably does just about  what you have in the script except for one variance.  We do not isolate the pyinstrument to profile just the  test code.

**Comment by KSchopmeyer** [comment]
Also, since I modified some things on the cmd line of run_response_performance they need to be changed in the script (i.e. table -> cprofile and stack -> pyinst

**Comment by andy-maier** [comment]
Abandoned, because Karl's python script now does all of that.

**Pull request closed without merging**
