### PR TITLE
Resource consumption tests

### PR DESCRIPTION
**Pull request by andy-maier**
Ready for review.
For details, see commit message.

Notes:
* There is no measurement of CIM-XML based resource consumption at this point. It would require adding server-side CIM-XML support to the mock environment, and that seemed too big of a task right now.

Output of `make resourcetest`:
```
tests/resourcetest/test_enuminst.py 
Resource consumption test: EnumerateInstances with num_props=1, num_insts=1:
  Elapsed time:        2.395 ms
  CPU time:            2.285 ms
  Peak usage:          38895 B
  Result size:          3960 B
.
Resource consumption test: EnumerateInstances with num_props=10, num_insts=100:
  Elapsed time:      230.473 ms
  CPU time:          229.457 ms
  Peak usage:         842896 B
  Result size:       1108848 B
.
Resource consumption test: EnumerateInstanceNames with num_props=1, num_insts=1:
  Elapsed time:        0.434 ms
  CPU time:            0.440 ms
  Peak usage:           6534 B
  Result size:          1416 B
.
Resource consumption test: EnumerateInstanceNames with num_props=10, num_insts=100:
  Elapsed time:      109.410 ms
  CPU time:          108.617 ms
  Peak usage:         131364 B
  Result size:         83252 B
.
```

### CODE REVIEW

**Comment by andy-maier** [comment]
I updated the PR to use the built-in `tracemalloc` instead of `memory_profiler`, and I added a `total_sizeof()` function that calculates the size of an object including its attributes and container items, and here is the result:

```
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=1):
  Elapsed time:        1.784 ms
  Result size:          3970 B
  Peak usage:          31395 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=10):
  Elapsed time:        9.435 ms
  Result size:         28386 B
  Peak usage:          42259 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=100):
  Elapsed time:       65.991 ms
  Result size:        273326 B
  Peak usage:         251890 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=1):
  Elapsed time:        5.797 ms
  Result size:         12717 B
  Peak usage:          52954 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=10):
  Elapsed time:       33.274 ms
  Result size:        113203 B
  Peak usage:         117347 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=100):
  Elapsed time:      239.756 ms
  Result size:       1105027 B
  Peak usage:         837660 B
```

What I don't understand yet is why the peak usage according to tracemalloc is sometimes less than the result object size.

**Comment by andy-maier** [comment]
Adding `__slots__` to all CIM object classes gives the following result:

```
tests/resourcetest/test_enuminst.py 
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=1):
  Elapsed time:         1.78 ms
  Result size:          2817 B
  Peak usage:          33284 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=10):
  Elapsed time:       10.163 ms
  Result size:         24139 B
  Peak usage:          42350 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=100):
  Elapsed time:       79.449 ms
  Result size:        236861 B
  Peak usage:         233430 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=1):
  Elapsed time:        5.919 ms
  Result size:         10346 B
  Peak usage:          61578 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=10):
  Elapsed time:        32.63 ms
  Result size:         95084 B
  Peak usage:         116426 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=100):
  Elapsed time:      259.095 ms
  Result size:        954287 B
  Peak usage:         763695 B
```

Using the 10 properties, 100 instances case, this is an improvement of:
* 13.5% in memory size of the EnumerateInstances result object
* 7.7% in elapsed time of the mocked EnumerateInstances

**Comment by andy-maier** [comment]
Adding `__slots__` also to the CIM types gives this result:

```
tests/resourcetest/test_enuminst.py 
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=1):
  Elapsed time:        2.369 ms
  Result size:          2745 B
  Peak usage:          33106 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=10):
  Elapsed time:         9.54 ms
  Result size:         23692 B
  Peak usage:          41740 B
.
Resource consumption test: test_enuminst_mock(num_props=1, num_insts=100):
  Elapsed time:       76.209 ms
  Result size:        232785 B
  Peak usage:         228574 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=1):
  Elapsed time:        6.063 ms
  Result size:         10105 B
  Peak usage:          60610 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=10):
  Elapsed time:       30.982 ms
  Result size:         92924 B
  Peak usage:         111718 B
.
Resource consumption test: test_enuminst_mock(num_props=10, num_insts=100):
  Elapsed time:      280.668 ms
  Result size:        921405 B
  Peak usage:         750587 B
```

Relative to the original code, this is a change of:
* 16.6% less memory size of the EnumerateInstances result object
* 16.8% more elapsed time of the mocked EnumerateInstances

**Comment by andy-maier** [comment]
Note that the latest results are now in the issues:
* issue #2509 for using `__slot__`
* issue #2511 for lazy creation of dicts

**Review by KSchopmeyer — APPROVED** [review]

**Pull request merged**
