### PR TITLE
Docs: Added installation and development sections.

### PR DESCRIPTION
**Pull request by andy-maier**
Please review.

This is improves the installation documentation in response to issue #506.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Couple of comments:

1. Intro.rst - The initial statement about it being pure python is correct but it into the next  paragraph before there is info about the issues with the dependencies. One sort of gets the wrong impression from that first paragraph.

3. Is there not one more way to install, pip directly from the git repository?

And NO I was not about to try the new review process that theyu announced this moring

2. Under installation we are pushing the use of virtual environments (word preferably) while serious users that are building other packages on top of this would use the virtual environments, as we put out more script level, I am assuming that these people don't care about virtual environments.  We probably need to clarify that.

**Comment by KSchopmeyer** [comment]
+1 with minor changes.

**Comment by andy-maier** [comment]
Made the suggested minor change, nearly as proposed.

**Comment by andy-maier** [comment]
Merging, as karl had already voted +1 with the minor change.

**Pull request merged**
