### PR TITLE
Fixes #609, fixes #536: Add recorder unit test

### LINKED ISSUE #59: Release version 0.8.1
DONE:
* Update NEWS file with latest changes, and commit/push.
* Build distribution archive, finalize README in dist 0.8 directory, and commit/push.
* Bump version in `setup.py` and NEWS file to 0.8.1, and commit/push.
* Create tag for 0.8.1 and push.
* Delete all preliminary 0.8 tags and push.
* Build and release API docs to GitHub pages (`make publish`, commit & push there)
* Update download table on GitHub pages installation page, and commit/push.
* Upload to PyPI (`make release`)
* Note on mailing list
* Close 0.8.0 milestone on GitHub

Unfortunately, I had to bump the version to 0.8.1, because I wanted to re-submit the archive file to PyPI, before I found out that they are really serious about not letting anyone replacing an already uploaded file.

### LINKED ISSUE #536: We have no unit test for the recorder
Since the recorder is a significant piece of code, we need at least a minimal test.  That wil:
1. Increase coverage
2. Reduce code errors like issue #351 since we will at least run the recorder.
3. Maybe even confirm the output format although I would make that a lower level priority.

This is being resolved as part of issue #676

### LINKED ISSUE #597: _recorder and things like property names have case errors
When we generate yaml with the recorder and then try to use it, we get a number of minor errors in the http comparisons because the names in the pywbem_request and pywbem_response items are lower case but what is in the http is mixed case.

For example:
```
  <CIM CIMVERSION="2.0" DTDVERSION="2.0">
    <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
      <SIMPLEREQ>
        <IMETHODCALL NAME="References">
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="root"></NAMESPACE>
            <NAMESPACE NAME="cimv2"></NAMESPACE>
          </LOCALNAMESPACEPATH>
          <IPARAMVALUE NAME="ObjectName">
            <INSTANCENAME CLASSNAME="PyWBEM_Person">
              <KEYBINDING NAME="CreationClassName (got: creationclassname)">
                <KEYVALUE VALUETYPE="string">PyWBEM_Person</KEYVALUE>
              </KEYBINDING>
              <KEYBINDING NAME="Name (got: name)">
                <KEYVALUE VALUETYPE="string">Alice</KEYVALUE>
```
This is because the recorder generates the yaml with lower case names for these things:
```
  pywbem_response:
    result:
    - pywbem_object: CIMInstance
      classname: PyWBEM_MemberOfPersonCollection
      properties:
        member:
          pywbem_object: CIMProperty
          name: Member
          value:
            pywbem_object: CIMInstanceName
            classname: PyWBEM_Person
            namespace: null
            keybindings:
              creationclassname: PyWBEM_Person
              name: Alice
```

Also we are getting other issues with operation parameters like the following in the recorder output:

      Role: null
      ResultClass: PyWBEM_MemberOfPersonCollection
      role: member

What we appear to be getting is the keybindings names in lower case in the recorder output for the
operation.  This then conflicts with the HTTP which has the correct case:
```
    operation:
      pywbem_method: AssociatorNames
      ResultClass: CIM_Collection
      Role: member
      AssocClass: PyWBEM_MemberOfPersonCollection
      ObjectName:
        pywbem_object: CIMInstanceName
        classname: PyWBEM_Person
        namespace: root/cimv2
        keybindings:
          creationclassname: PyWBEM_Person
          name: Alice
      ResultRole: Collection

      <IPARAMVALUE NAME="ObjectName">
      <INSTANCENAME CLASSNAME="PyWBEM_Person">
      <KEYBINDING NAME="CreationClassName">
      <KEYVALUE VALUETYPE="string">PyWBEM_Person</KEYVALUE>
      </KEYBINDING>
      <KEYBINDING NAME="Name">
      <KEYVALUE VALUETYPE="string">Alice</KEYVALUE>
      </KEYBINDING>
```

Also, at least for the associatorNames, the host is not included in the recorder output:
```
  pywbem_response:
    result:
    - pywbem_object: CIMInstanceName
      classname: PyWBEM_PersonCollection
      namespace: root/cimv2
      keybindings:
        instanceid: PersonCollection
```

but is in the http response:

```
      <IMETHODRESPONSE NAME="AssociatorNames">
      <IRETURNVALUE>
      <OBJECTPATH>
      <INSTANCEPATH>
      <NAMESPACEPATH>
      <HOST>sheldon</HOST>
      <LOCALNAMESPACEPATH>
      <NAMESPACE NAME="root"/>
      <NAMESPACE NAME="cimv2"/>
```

### LINKED ISSUE #609: Recorder output is all with indent=2. The norm for everything else is indent=4
Having the indent=2 makes it difficult to work with the results and any editing often leasts to messy results.  We would be better if we kept everything at indent=4

### LINKED ISSUE #663: recorder fails in testclient test ValidResponse5.yaml
I added code to use the recorder output on all tests in testclient.  It fails on the testValidResponse5.yaml
with the following error:

Traceback (most recent call last):
  File "testsuite/test_client.py", line 503, in test_all
    self.runyamlfile(relfn)
  File "testsuite/test_client.py", line 514, in runyamlfile
    self.runtestcase(testcase)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/httpretty/core.py", line 1146, in wrapper
    return test(*args, **kw)
  File "testsuite/test_client.py", line 691, in runtestcase
    (tc_name, op_name, raised_traceback_str))
AssertionError: Testcase ValidResponse5: No exception was expected to be raised by PyWBEM operation GetInstance, but an exception was actually raised:
Traceback (most recent call last):
  File "testsuite/test_client.py", line 621, in runtestcase
    result = op_call(**op_args)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_operations.py", line 5835, in GetInstance
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/_recorder.py", line 335, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/_recorder.py", line 500, in record
    self._fp.write(data)

UnicodeEncodeError: 'ascii' codec can't encode character u'\ud7ff' in position 1059: ordinal not in range(128)

The error is legitimate in that it is the illegal unicode test... Have not looked further to see if there is other issue but this does stop the test whereas without recorder, the test cases continue.  

NOTE: I created the test by simply turning on the recorder in test client with output to dev/dull

### LINKED ISSUE #676: Recorder issues
Several issues with the recorder as follows:

1. indent output yaml by 4 to be more consistent with normal use. Include issue # 609 in this, set indent to 4 (currently 2)
2. Issue where open/pull does not correctly return context info.
It returns:
```
pullresult:
        - true
        - null
```
Where is should be in the form

```
        pullresult:
            context:
                - blahblah
                - root/cimv2
            eos: false
```

3. (New problem) Recorder does not write utf-8 in python 2.7.  Fixed for now by modifying the open in both run_cim_operations.py and test_recorder.py to use codecs.open(...) with python 2.

4.  (New problem)  Issue with recorder writing and then testing some datetime properties.  Results cannot be compared. Produces an exception stating that naive and timezone aware cannot be compared. Working solution in test_recorder.py is to insure that all datetimes are timezone aware.  See issue #698

5. Exception from run_cimoperations.py, Representer cannot handle datetime.
Actually, the representer cannot handle the python timedelta type.  Datetime appears to pass through
correctly.  The solutions are a) find some way to bypass that particular type, or b) extend the representer to handle timedelta correctly NOTE: This issue moved to issue#702

```
======================================================================
ERROR: test_non_empty_arrays (__main__.InvokeMethod)
Call with non-empty arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 2359, in test_non_empty_arrays
    RefArray=[name, name])
  File "testsuite/run_cim_operations.py", line 169, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 6961, in InvokeMethod
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 352, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 514, in record
    default_flow_style=False)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: 00000000000000.000000:000
```

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Fix for issue #609 indent by 4 -  Done
Fix #536, recorder unit test - Done Coverage is at 70-71% now
Fix #676 - No representer for timedelta (not done). This one is a bear.  I have a special test for this in the code now but it has a patch so that it does not error out. 

Fix #663, Test_client fails test testValidResponse5 which attempts to use nont ascii utf-8 characters.
The change to the _recorder open for this pr should fix that issue also.
Fix #597 - Case of properties. - Not done. Actually cannot recreate that one  which is why I added more tests directly generated to testclient yaml files.
Fixed code that produces pywbem_repsonse context, eos, etc.  That works and has test in recorder unit test.
At least temp fix for utf-8 issues by fixing in run_cim_operations.py and test_recorder.py.  With 2.7, open
with codecs.open.

Added some examples of results generated directly from the generator to testclient.  They can be
identified by the statement Generated by TestClientRecorder as part of the description.

There is one new one, createinstance that was created as test directly by the generator but is broken. It has many properties in the instance to be created but test_client gets an error comparing the http response but neither the original or test http has all the properties defined in the test.  I marked it ignore_test for the moment.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
At this point we have fixed most problems and created the unit test.   However, one of the key issues remains, the roundtrip  record -> yaml load of time delta fails at least in one of the tests and for some reason, the generator build very large create instance appears not to test all of the http components. The actual and expected show different number of properties in the http compare and neither is right.

Should we commit what we have and write new more limited problem or try to clean up in this pr??

**Comment by andy-maier** [comment]
Let's commit this and solve that issue separately.

**Comment by KSchopmeyer** [comment]
The remaining issues were documented in issue #701 and #702

**Comment by KSchopmeyer** [comment]
We are repeatedly failing travis tests now because of timeout getting swig.

**Comment by KSchopmeyer** [comment]
+1

**Comment by KSchopmeyer** [comment]
Whoopee

**Comment by andy-maier** [comment]
+1

**Pull request merged**
