### PR TITLE
Fixes #375: Missing indications

### LINKED ISSUE #375: pegasusindicationtest.py script misses indications
PR #367 introduced `examples/pegasusindicationtest.py`. This script invokes a method of OpenPegasis that causes a specified number of indications to be sent.

However, the script only receives a subset of them.

Investigate where the problem is.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Pls Review. Ready for Merge. 3 July 2016 

This pr corrects issues that were causing massive indication lost between pegasus server and listeners.  Specifically this fixes some issues in the listener that was causing responses to get lost and some issues in the tests that were causing failures with pegasus indications.

It creates a new test sender in python sendIndications.py in the example directory and fixes some errors in listener just to be sure the issue was not with the shell script sender.

Modifies the send_indication.sh to send multiple indications and adds argument parser for better understanding.  NOTE: Not really sure we need this in the future.  the corresponding sendIndications.py is parallel in operation and does not depend on curl, and will be more complete.

The good news is that we are probably not losing indications now.  The bad news is that we are  receiving more than are sent.  Send 2, and the indication listener says we got 3. Send 200 and it says we received 400.  Looks like somewhere we have issues in resending, etc.

### CODE REVIEW

**Comment by andy-maier** [comment]
Karl:

* I don't understand how the changes in `_listener.py` fix the issue.

* Also, you stated in another issue that indications would not have an ack. That is not true, DSP0200 defines a response message, and our listener sends that back. It always sends either an error response or this success response. 

* On adding the XML header line: The literal string is defined as a binary string. Not sure what the `toxml()` returns in terms of binary vs unicode. I think the + operator combines them correctly, by converting the second string to the kind of the first string. I would prefer to have that conversion explicit, if only to state what the encoding is.

**Comment by KSchopmeyer** [comment]
There may be another issue in that when the example program tries to deliver more than about 10000 indications, we lose lots of them.  Just ran a test and it seemed to stall somewhere between 5000 and 20,000. Remember that we are shoving a solid stream of indications out with no delays except for the ack

**Comment by andy-maier** [comment]
Discussion points:

* Use of binary vs. unicode when adding the XML header.
* Remaining issues with lost indications.
* Making sure subscriptions get cleaned up even in error or break cases.
* Reuse existing subscriptions when about to create new ones.

**Comment by KSchopmeyer** [comment]
Mesasuring iindication flow:

The following are some statistics from the pegasus indication test program.  Interesting that per sec stats are widly idvergent even for a count of indications sent.   There is still something going on that I do not understand.

```
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 1000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=1000
Rcvd 1000 indications in 03 sec; 333 per sec. Exit wait loop
Success, 1000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 1000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=1000
Rcvd 1000 indications in 3.005088 sec; 333 per sec. Exit wait loop
Success, 1000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 2000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=2000
Rcvd 2000 indications in 36.039848 sec; 55 per sec. Exit wait loop
Success, 2000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 2000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=2000
Rcvd 2000 indications in 6.012311 sec; 333 per sec. Exit wait loop
Success, 2000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 2000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=2000
Rcvd 2000 indications in 35.043727 sec; 57 per sec. Exit wait loop
Success, 2000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 2000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=2000
Rcvd 2000 indications in 65.073753 sec; 31 per sec. Exit wait loop
Success, 2000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 2000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=2000
Rcvd 2000 indications in 36.045633 sec; 55 per sec. Exit wait loop
Success, 2000 indicatons
(pywbem27)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./pegasusindicationtest.py http://127.0.0.1 5000 ks ks 1000
url=http://127.0.0.1 listener=127.0.0.1 port=5000 usr=ks pw=ks cnt=1000
Rcvd 1000 indications in 3.003696 sec; 333 per sec. Exit wait loop
Success, 1000 indicatons
```

**Comment by KSchopmeyer** [comment]
We agreed to move the issue of loading to the next version, to add a user defined prefix to names, and to not worry about reusing instances until the next version.

**Comment by KSchopmeyer** [comment]
+1  I moved the individual issues to other new issued, changed the binary concatenate to just string (turns out that right now toxml returns a string (filed an issue on this since I think this can be more efficient.

**Pull request merged**
