### PR TITLE
Fixes #259: Added section 'Standards conformance' to documentation

### LINKED ISSUE #259: We should document relation to specs
We should have a spec compiiance document that documents

1. Which specifications and which versions of the dmtf specs we support
2. Any compilance issues and functionality we specifically do not support in the dmtf specifications

### PR DESCRIPTION
**Pull request by andy-maier**
Ready to be merged.
Please review.

Note: This change already includes what the additions from the ``listener`` branch conform to, with a TODO to be finalized / adjusted / removed once that branch gets merged.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
-1. I think we are going to have to get down to spec version numbers. 

Should we also mention DSP0004 for the model since we do conform to that?

**Comment by andy-maier** [comment]
* On spec version numbers:
  They are in the references section, and the standards conformance section says that they apply.

* On DSP0004 and model:
  It would be the metamodel. I was thinking about where that would practiually apply, and found it applies to the CIM objects, where the current text states conformance to DSP0004.
  But maybe we should extend that to also mention the "metamodel supported by PyWBEM" or something like that. I'll do that.

**Comment by andy-maier** [comment]
Commit 90c46e4 addresses the second comment.

Please let me know whether we need to do something about the first comment.

**Comment by KSchopmeyer** [comment]
Lets just state the specs with the versions as defined in the conformance section. We don't want to duplicate but we do want people to understand that the spec version is important.

**Comment by KSchopmeyer** [comment]
+1

**Comment by andy-maier** [comment]
Karl reviewed the latest commit in the call today, and agrees to go forward with this one.

**Pull request merged**
