### PR TITLE
Fixes #526: Moved compat_args.py from testsuite/ to try/

### LINKED ISSUE #526: testsuite/compat_args.py. Is there any reason to keep this in testsuite?
This is not really part of the test suite.  Should we move it to tools?

### PR DESCRIPTION
**Pull request by andy-maier**
As agreed for issue #526.
Please review

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
+1 My only confusion is the name of the directory try.  We agreed to that but in restrospect I am not sure what a directory named try really means.

**Comment by andy-maier** [comment]
**Discussion point:** Directory name

**Comment by andy-maier** [comment]
We used `try` only because that's my standard directory name for things to "try out". We discussed this again in the call today and because none of us was able to come up with a better name, we decided to go with `try`.

**Pull request merged**
