### PR TITLE
Fixes #461: Recovering owned destination, filter and subscriptions upon server add.

### LINKED ISSUE #461: Recover owned instances when restarting subscription manager
When a Python program that uses a `SubscriptionManager` instance dies, there may have been CIM instances created that were owned by the `SubscriptionManager` instance. Currently, these instances are neither cleaned up while dying, nor are they rediscovered when the subscription manager restarts.

It would be good to come up with an approach by which a subscription manager could rediscover existing CIM instances on a server that were owned, and again consider them owned instances.

The difficulty to resolve is how the new `SubscriptionManager` instance can safely be considered a restarted old one? Maybe via the `subscription_manager_id` value? Do we need to prevent that two `SubscriptionManager` instances have the same `subscription_manager_id` value and thus both assume ownership of existing previously owned instances?

### PR DESCRIPTION
**Pull request by andy-maier**
This PR does not include a testcase.

Please review.

Details:
- Inserted an indicator for ownership into the `Name` property of filters and destinations (`"owned"` vs. `"permanent"`).
- Made subscription manager ID mandatory (must not be None), because it is now used for recognizing owned instances.
- Made filter ID mandatory for the same reason.
- Added code in `add_server()` to determine owned destinations and filters by matching their `Name` property, and to determine owned subscriptions if they reference an owned filter or an owned destination.

### CODE REVIEW

**Comment by andy-maier** [comment]
We need to discuss the approach, as well as issue #540.

**Comment by KSchopmeyer** [comment]
We concluded that we may have one significant problem with this in that profiles may set requirements on the Name property. Andy opened issue

**Comment by andy-maier** [comment]
Issue #540 describes that remaining problem, and we agreed that we would handle that in a separate PR.

So this PR is ready to be merged (whtout adressing issue #540). Please review and vote.

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
