### PR TITLE
Add support for TYPE attribute in PARAMVALUE

### PR DESCRIPTION
**Pull request by tony23**
As discussed at https://github.com/pywbem/pywbem/issues/1241

My apologies if I'm doing this wrong, I haven't worked with OS projects in a very long time.

### CODE REVIEW

**Comment by andy-maier** [comment]
Tony, no problem. We help you!
The reason it fails on Travis is that some source formatting is incorrect. See the Travis logs. You can run that locally with:

```
make check test
```

**Comment by KSchopmeyer** [comment]
Per the failed tests, the following fixes have to be made to pass our tests.

testsuite/test_tupleparse.py:9802:81: E501 line too long (94 > 80 characters)
testsuite/test_tupleparse.py:9813:81: E501 line too long (99 > 80 characters)
testsuite/test_tupleparse.py:9824:81: E501 line too long (99 > 80 characters)
testsuite/test_tupleparse.py:9832:81: E501 line too long (86 > 80 characters)
testsuite/test_tupleparse.py:9835:81: E501 line too long (99 > 80 characters)
5     E501 line too long (94 > 80 characters)

As andy said,  run make check and it will find those issue. then run the whole process

ex. make clobber all which does everything, develop, install, build check test.

We specifically require that all code pass the  flake8 tests to pass the continuous integration test suite.

Luckly, we do not require that it pass all pylint tests since we are still beating some of those out of the code from years ago.

**Comment by tony23** [comment]
Hi, My apologies for dropping the ball on this. I let myself get sidetracked and forgot it was out there.

I'm having some difficulty getting the tests to actually run correctly on the environment I'm using. Not sure what the problem is but I'm going to try again with a different env. Will advise on the results.

**Comment by KSchopmeyer** [comment]
Karl and Andy agreed wed 4 July to try one more time early next week to contact Tony and if the does not work, simply to integrate this work ourselves.

**Comment by tony23** [comment]
I'm seeing "continuous-integration/appveyor/branch..." check still reporting "Waiting for status to be reported" after 24 hours. Is there anything else that I need to do to get this change ready to merge?

**Comment by andy-maier** [comment]
Tony, I believe this probably was a one-time error in the environment. These things have happened to me as well. The usual way to get over this is to rebase the PR (`git rebase -i master`) and to force-push it (`git push -f`), which will trigger a new round of CI runs.

**Comment by andy-maier** [comment]
Second, please see the comments we made further up, regarding changes to get the CI runs pass.

**Comment by tony23** [comment]
Made the changes already in that commit, trying your rebase suggestion.

**Comment by tony23** [comment]
That didn't seem to trigger anything, so I made a small whitespace change, then changed it back. Hopefully everything will run this time.

**Comment by andy-maier** [comment]
You're really out of luck with Appveyor, Tony. Let me try it.

**Comment by andy-maier** [comment]
I merged the content of your PR into a branch on this repo and created a aPR for that, and that worked fine.

So I suspected that there is something not set up correctly when comeone pushes from their fork of this repo, and that was indeed the case. This did not work either, with the same symptom, when I created a PR from a branch on my fork.

Then I played around with the Appveyor setup and found that the event "create a PR" does work from forks, but "push" does not. Which makes sense, because after all the only action you are doing to this repo is creating a PR, but the push goes to your fork.

So I changed the Appyevor setup now to process only the "Create a PR" event, but no longer the "Push" event.

**Comment by andy-maier** [comment]
Closing and reopening this PR triggered the CI runs for both Travis and Appveyor.

**Comment by andy-maier** [comment]
Tony, this PR is all set now. Thanks for providing it! I have approved it and am merging it.

In the future, PRs from your fork should properly trigger the CI runs due to the change in setup described above.

**Pull request merged**
