### PR TITLE
[WIP] Fixes #682: Add new ipython notebooks

### LINKED ISSUE #682: Add python notebooks for pull and iter operations
We need to add notebooks to define both the iter and pull operations.  In general this is about 16 notebooks but even if we just add a few, it helps

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Added notebooks for

*  Pull operations - A single notebook with TOC
* Iter... operations - A single notebook
*  WBEMServer class

WIP Today because there are a number of TODOs, primarily sections and examples that are incomplete.

I included a toc generator in the tools directory. It is manual now so you have create the toc and manually insert into the notebook.  You also have to update when you change the sections in a notebook

Extended the tutoral page to include the new notebooks

Added to changes.rst

Comments welcome but I know I have more work on this one.  There are several TODOs and I think I was messy in some of my text.

### CODE REVIEW

**Comment by andy-maier** [comment]
Karl,
we should not delete the branch of this PR when we merge it.

Reason is that I ran into sn issue with the online nbviewer when trying to render one of the notebooks on this branch. I opened issue jupyter/nbviewer#691, and they may want to verify the issue using this branch here, or test a solution.

**Comment by andy-maier** [comment]
Karl, there are several small issues that I'd like to fix directly instead of writing comments.

**Comment by andy-maier** [comment]
I'm done for now with direct updates.

**Comment by KSchopmeyer** [comment]
Points to concepts section for overview material.  Removed TODOs.

**Comment by KSchopmeyer** [comment]
NOTE: Right now may hyperlinks are to latest doc, not stable. Also, we point to concepts, not the specific sections in concepts.

**Comment by KSchopmeyer** [comment]
Cleaned up the overview to point to the correct sections of the concepts.

**Comment by andy-maier** [comment]
+1

**Pull request merged**
