### PR TITLE
Fixes #598: Fixed issue with ref class check in CIMProperty.

### LINKED ISSUE #598: reference instances return REFERENCECLASS property in test_client
in the test case referenceinstance1 (part of pr589) we are getting the following error on the
response:

  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.10.0.dev0-py2.7.egg/pywbem/cim_obj.py", line 498, in _intended_value
    % (name, actual, intended))
ValueError: Property u'Member' has a CIMInstanceName value with classname=u'PyWBEM_Person', but specifies reference_class=u'CIM_ManagedElement' (must be u'PyWBEM_Person')

Not yet sure what this means.  This works in run_cim_operations and I think that CIM_ManagedElement is the correct response so we may actually have an issue in cim_obj.py but not sure yet.

I wanted to gather as much data as possible now.
I think I have isolated the problems. See reasons in following comment block

### PR DESCRIPTION
**Pull request by andy-maier**
**Note:** This PR is on top of PR #738.

This PR is now complete and is ready for review and merge.

@KSchopmeyer: Karl, if you still want to extend the testcases, it would probably be easier if you did that in a separate PR on top of this PR.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Not yet sure what problem is but this is dying ig GetAllTypes1 test.  It also fails ReferenceInstances1, the onethat is marked ignore_test but the error is in Test_client iteslf, not in cim_obj.py.  Will look forther later tonight

**Comment by KSchopmeyer** [comment]
The test is dying in test_client apparently OpenReferenceInstancePaths1. 

Changing the tupleparser affects nothing.

However, restoring the original code in cim_obj.py causes test_client to succeed (not that this is without the ReferencesInstances1 test which is the one that was failing originally)

**Comment by andy-maier** [comment]
We found out that testcase `GetAllTypes1` in `test_client/getalltypes.yaml` was missing to specify `reference_class` attributes for its `PRef1` and `PRef2` properties. They had previously be inferred from the classname of the CIMInstancePath, but that was exactly the fix of this PR to no longer do that. So they now need to be specified explicitly in the testcase.

**Comment by andy-maier** [comment]
I made the fix that we discussed in the call, and made it in such a way that one reference property returns the REFERENCECLASS attribute, and the other does not.

I also rebased this PR on top of PR #738 to circumvent the recent flake8 issue.

**Pull request merged**
