### PR TITLE
Fixes and improvements in makefile

### PR DESCRIPTION
**Pull request by andy-maier**
This addresses issue #41 and some other issues.

Details, from the commit message:
- Added dependents for Lex/Yacc table files (mofparsetab.py/moflextab.py).
- Made sure that mofparsetab.py and moflextab.py are generated in the right
  directory (pywbem package directory) even when mof_compiler.py is invoked
  standalone.
- Bad return codes from py.test and epydoc are now surfaced as make errors
  (solves issue #41).
- Changed meaning of 'clean' target to be cleanup before other make targets.
- As a result, 'clean' target now removes anyhting that is dependent on
  Python version but has same file name.
- test.log now has a Python version dependent name (e.g. test_27.log).
- Made 'all' target consistent with tox and Travis invocations (i.e. removed
  build+install, because that is done by the 'develop' target already, and
  moved 'clean' target to the front).

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Let me look this one over for an hour or so.  My only real question is on the level of dependents for lex and yacc table files.

**Comment by andy-maier** [comment]
On the dependents: I added all modules that are used by mof_compiler, on the argument that if they are used, they could influence the output. So the table files are now re-built more often.

**Comment by KSchopmeyer** [comment]
Not sure if necesssary but it is certainly safer.  Would have to dig into all dependencies in mof_compiler to be sure.

**Comment by andy-maier** [comment]
I have added all modules that mof_compiler uses, recursively.

**Comment by andy-maier** [comment]
Rebased it on master.

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
I sent andy some questions that appeared to me but it was after the commit. Primarily why the heavy detail output for tests now and second, we are getting an exception on a test but it may be just that we are seeing it now because of the detail test processing output.

**Comment by KSchopmeyer** [comment]
Whoops.  Error in the part of comment above about commit.  It is not committed.  I sent andy a detailed display of the test output in the new branch including the test that generated the exceptions

**Comment by KSchopmeyer** [comment]
Other than the question about the change to test output level and understand if the failure shown is new or just more visible I am ready to approve this pull request

**Comment by andy-maier** [comment]
* On the heavy detail output for tests: I added the `-s` option to `py.test` which causes stdout/stderr of the unit test modules to be displayed instead of being captured and lost. The only test module that produces output is test_client, which has only one testcase as known to py.test, so its report about yaml files and testcases within those gives some more information. Also, any debug prints added to the test cases are shown that way. We can turn that back by simply removing the `-s` option again. Let me know.
* On the exceptions that are shown: The ones I can see are the exceptions that result from the testcases intentionally raising them. See also issue #21 describing these same exceptions. I do not yet understand why that is shown by py.test, when they are expected. Maybe it has to do with multi-threading. For now, I think their display does not hurt, and the tests that have them rightfully count as passing.

**Comment by KSchopmeyer** [comment]
+1  approved
Lets leave the -s option in for now since it gives us more info. At some point it should probably become a formal makefile variable (verbose) since once this settles down not everybody will want to see the details but we can leave that for the future.

Yes. It is strange in that the exceptions actually tear output apart (inserted right in the middle of the word succeed in the output terminal indicating that a it is a threading thing, b)somewhere we are not providing enough multithread control on output.

**Comment by andy-maier** [comment]
Ok. Merging it.

**Pull request merged**
