### PR TITLE
Fixes #126: Fix support for embedded instances

### LINKED ISSUE #126: Support for embedded objects/instances missing in parameters and method return
DSP0004 clarified at some point that method parameters and return values may also be embedded objects or embedded instances. This support is missing in pywbem, at least for the representation of such methods in classes. I believe it is supported for actual method invocation, but this needs double checking.

### PR DESCRIPTION
**Pull request by andy-maier**
Ready to be reviewed and merged.

This PR cherry-picked the commit from PR #438, in order to succeed in Travis CI.
Update: The cherry-picked commit has been merged in the mean time, so the rebase eliminated it again.

For details, see the commit messages.

### CODE REVIEW

**Comment by andy-maier** [comment]
Commit  	5a1a1a0  is the final part of this MR for XML-escaped embedded instances.

I suggest to merge this PR, even though not all test cases have been written.

I'll open a new issue for the remaining test cases (that involve CDATA-escaped embedded instances, as well as embedded objects that are instances or classes.

**Comment by andy-maier** [comment]
+1

**Comment by andy-maier** [comment]
We agreed in the call to defer the other test cases as proposed, and to review this PR in its current scope.

**Comment by andy-maier** [comment]
Rebased.

Note that technically, a rebase was not needed because git will ignore the commit that was cherry-picked because it was already merged. However, for looking at the changes I can see that it is easier, so I rebased.

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
