### PR TITLE
Fixes #165: Added shell script for install testing (testsuite/test_install.sh).

### LINKED ISSUE #165: Document install tests
Before each release, we should run an install test.

Document the install tests.

Input on the test variations, from PR #143:
- Installer: `pip install` e.g. from local dist archive / `setup.py install` from repo work dir.
- MOF table files: missing / present with non-matching versions / present with correct versions.
- Prerequisite packages for building MOF table files (`six`, `ply`, `M2Crypto`): installed / not installed.
- Python env: system python with sudo, virtual python without sudo.

### PR DESCRIPTION
**Pull request by andy-maier**
This PR adds a shell script `testsuite/test_install.sh` that performs installation testing.
Also, it updates the DEVELOP.md file to document that it should be run during the final release tests.
Please review, and try out the shell script.

### CODE REVIEW

**Comment by andy-maier** [comment]
Now ready for review.
Tested it on CentOS 7 and Ubuntu 14.04.

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
+1  The only thing that worries me about this is that we are adding more and more install requirements for the develop environment.  Thus this one adds the whole mkvirtualenv as a requirement.  Probably logical but in the past we tried to minimize external requirements and in this python environment we are doing the opposite.

**Comment by andy-maier** [comment]
I did not add the mkvirtualenv requirement to "develop_requires" or to "develop_os_requires". The script is really meant to be run manually, and for tox, you need virtualenv anyway (although not virtualenvwrapper). I just don't know how else the install test could work.

**Comment by andy-maier** [comment]
I take your +1, and merge this one.

**Pull request merged**
