### PR TITLE
Fixes #178: Moved exceptions into new module 'exceptions' and derived all from 'Error'

### LINKED ISSUE #178: Inconsistency: ParseError is not derived from Error
Exception `tupleparse.ParseError` is the only externally visible exception that is not yet derived from `pywbem.Error`. I suggest to change `ParseError` to be derived from `Error`.

That means the exceptions need to be shuffled around a bit. One option would be to move all of them into a new sub-module. We can leave alias symbols in the modules that define them today, for compatibility.

Needs discussion on how to do that.

### PR DESCRIPTION
**Pull request by andy-maier**
Ready for merge; please review.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
I want to take a little more time with this one.

**Comment by andy-maier** [comment]
Rebased it to resolve merge conflict in changes.rst.

**Comment by KSchopmeyer** [comment]
Reviewed, tested and I don't even have any comments this time. +1. Only thing I did not do was to go through pylint for new issues.

+1

**Pull request merged**
