### PR TITLE
Fixes #1631: Moved make shell commands into scripts for Windows

### LINKED ISSUE #1631: Got Error in Windows while executing PyWBEM
I'm new to PyWBEM and got this issue while executing this script

(tools) D:\Soft\PyWBEM\pywbemtools\pywbemtools>workon tools
(tools) D:\Soft\PyWBEM\pywbemtools\pywbemtools>make develop
  File "<string>", line 1
    import sys; sys.stdout.write('s.sys.version_info[0:3])
                                                         ^
SyntaxError: EOL while scanning string literal
  File "<string>", line 1
    import sys; sys.stdout.write('sys.version_info[0])
                                                     ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'str' object is not callable
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
  File "<string>", line 1
    $(printf 'try:\n from pbr.version import VersionInfo\nexcept ImportError:\n pass\nelse:\n print(VersionInfo(\042pywbemtools\042).release_string())\n')
    ^
SyntaxError: invalid syntax
wget -q http://pywbem.readthedocs.io/en/latest/_downloads/pywbem_os_setup.sh
process_begin: CreateProcess((null), wget -q http://pywbem.readthedocs.io/en/latest/_downloads/pywbem_os_setup.sh, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [pywbem_os_setup.sh] Error 2

(tools) D:\Soft\PyWBEM\pywbemtools\pywbemtools>https://github.com/pywbem/pywbemtools.githttps://github.com/pywbem/pywbemtools.git

### PR DESCRIPTION
**Pull request by andy-maier**
For details, see the commit message.

Test: Raamesh wantes to test this on native Windows, see issue #1631.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
I reviewed the code with  no issues.

However, trying to test in a windows system that has a make I hit  several issues immediatly:

1. does not install pbr.  Did pip install pbr to get around that.

2. Issue with curl. This  environment includes curl and it can be called from the cmd line but the make environment does not find it.

```

(pywbem27) C:\Users\kschopmeyer\dev\pywbem\pywbem>make install
"makefile: Installing OS-level installation and runtime requirements"
"Debug: PATH=C:\Users\stduser\Envs\pywbem27\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\cvsnt;C:\bin;C:\bin\usr\local\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Bitvise SSH Client;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\stduser\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\stduser\AppData\Local\Programs\Python\Python37-32\;C:\Users\stduser\AppData\Local\Microsoft\WindowsApps;"
cmd /d /c pywbem_os_setup.bat install
Current Python is: Version 2,  64-bit
Installing OS-level prerequisite packages for install on platform Windows ...
Swig is already installed ... skipping
Installing Win64OpenSSL-1_1_0j ...
curl -o Win64OpenSSL-1_1_0j.exe -sSL https://slproweb.com/download/Win64OpenSSL-1_1_0j.exe
'curl' is not recognized as an internal or external command,
operable program or batch file.
Error: Command returned rc=9009
make: *** [install_os.done] Error 9009

(pywbem27) C:\Users\kschopmeyer\dev\pywbem\pywbem>which curl
which: no curl in (C:\Users\stduser\Envs\pywbem27\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\cvsnt;C:\bin;C:\bin\usr\local\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Bitvise SSH Client;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\stduser\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\stduser\AppData\Local\Programs\Python\Python37-32\;C:\Users\stduser\AppData\Local\Microsoft\WindowsApps;)

(pywbem27) C:\Users\kschopmeyer\dev\pywbem\pywbem>curl -h
Usage: curl [options...] <url>
     --abstract-unix-socket <path> Connect via abstract Unix domain socket
     --anyauth       Pick any authentication method
 -a, --append        Append to target file when uploading

(pywbem27) C:\Users\kschopmeyer\dev\pywbem\pywbem>curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

(pywbem27) C:\Users\kschopmeyer\dev\pywbem\pywbem>make --version
GNU Make version 3.79.1, by Richard Stallman and Roland McGrath.
Built for Windows32
Copyright (C) 1988, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 2000
        Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

Report bugs to <bug-make@gnu.org>.

**Comment by KSchopmeyer** [comment]
Accidently hit the close and comment button and then reopened.  

This could all be my environment problems since trying just to get gnu make enabled on windows is a task but that is what I found on first tests.

**Comment by andy-maier** [comment]
Hi karl. I have updated this branch by calling external commands from pywbem_os_setup.bat with "call", just in case someone has a curl.bat or curl.cmd. Also, I have added support for installing curl using Chocolatey if "where curl" fails. The "where" command is the built-in "which" of native Windows.

Please try again with this branch. Please try this on half-way set up environments as well as on environments that are reasonably fresh (e.g. freshly created virtual python env, run `make clobber`).

**Comment by KSchopmeyer** [comment]
Started testing on windows. Testing with existing virtual env first. Note that this make I am using is the old gnumake but that there is also a bash but VERY old in the same directory.

1. hit problem with clobber

```

(pywbem3) C:\Users\kscho\dev\pywbem>make clobber
makefile: Removing temporary build products
/bin/find . -name '*.pyc' -delete
/bin/find: invalid predicate `-delete'
make: *** [clean] Error 1

2. make build worked (executed install also)

3.Had to manually install flake8.  But that could be issue with my existing virt env.

Installed flake8 with pip.  flake8 works.

However, make check fails.  Cannot find flake8. This is probably because it is doing:

/bin/bash: flake8: command not found


4. Of course make test fails for same reason. Trying to use bash but under windows.

**DISCUSSION:** How far do we want to go with making the development environment work under window???  What all should be in the develop environment in order to do a make with pure windows?
i.e are we requiring bash???  That is a question right now, since I am not sure.

**Comment by KSchopmeyer** [comment]
lets try:

bash invocation in make that shows path.  Looks like we are getting the windows bash now and for some reason, the path is not correct.

**Comment by andy-maier** [comment]
In the latest update to this PR, I removed any use of bash, tee, xargs, rm, find, touch on native Windows. So far, I tested it just on Appveyor (which has Cygwin in the PATH, does not invoke all make targets, and which runs on Windows 8.1).

So a truly native Windows 7 without any UNIX-like environment in the PATH would be a good test.

**Comment by KSchopmeyer** [comment]
New Tests: Saturday with fresh checkout:
With new virtual env:
1. Develop completes
2. build completes
3. check creates .done file and executes flake8 with correct output
4.wbemcli loads and shows help
5. however, after check creates its done file, not sure how to get rid of the .DONE file.  I erase it and can do another "make check"

5. Problems start with make test. It does not execute any tests.

```


(pywbem3wintest) C:\Users\kscho\dev\pywbem3wintest\pywbem>make test
make[3]: Entering directory `C:/Users/kscho/dev/pywbem3wintest/pywbem'
makefile: Creating the LEX/YACC table modules
cmd /c del /f /q pywbem\\mofparsetab.py* pywbem\\moflextab.py*
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

(pywbem3wintest) C:\Users\kscho\dev\pywbem3wintest\pywbem>dir *.done
 Volume in drive C is OS
 Volume Serial Number is DE63-2E0A

 Directory of C:\Users\kscho\dev\pywbem3wintest\pywbem

02/09/2019  12:16 PM                 5 develop.done
02/09/2019  12:14 PM                 5 develop_os.done
02/09/2019  12:37 PM                 5 flake8.done
02/09/2019  12:14 PM                 5 install.done
02/09/2019  12:14 PM                 5 install_basic.done
02/09/2019  12:14 PM                 5 install_os.done
02/09/2019  12:14 PM                 5 install_pywbem.done
02/09/2019  12:14 PM                 5 pip_upgrade.done
               8 File(s)             40 bytes

6. Tried indivdual tests.
 Some work fine:
    test_cim_http.py, 

but others fail almost completely:

   test_cim_obj.py
   test_cim_xml.py - Every test but one failed.

Looks like it is tied to str, vs bytes and differences between windows and other reasonable platforms

```

        # Make sure the validator checks the specified root element, if any
        if root_elem_name is not None:
            cim_xml_str = u'<!DOCTYPE {0} SYSTEM "{1}">\n{2}'. \
                format(root_elem_name, dtd_file_fw, cim_xml_str)
            xmllint_cmd = 'xmllint --valid --noout -'
        else:
            xmllint_cmd = 'xmllint --dtdvalid {0} --noout -'.format(dtd_file_fw)
    
        p = Popen(xmllint_cmd, stdout=PIPE, stderr=STDOUT, stdin=PIPE, shell=True)
    
        cim_xml_str = _ensure_bytes(cim_xml_str)
        p.stdin.write(cim_xml_str)
        p.stdin.close()
    
    >       output = '\n'.join(p.stdout.readlines())
    E       TypeError: sequence item 0: expected str instance, bytes found

I attached the output of pytest tests/unittest/pywbem/test_cim_xml.py

[test_cim_httppyOutput.txt](https://github.com/pywbem/pywbem/files/2848178/test_cim_httppyOutput.txt)

Just in case this could be tied to package versioning here is pip list output:

```
(pywbem3wintest) C:\Users\kscho\dev\pywbem3wintest\pywbem>pip list
Package                  Version       Location
------------------------ ------------- ----------------------------------------
alabaster                0.7.12
atomicwrites             1.3.0
attrs                    18.2.0
Babel                    2.6.0
backcall                 0.1.0
bleach                   3.1.0
certifi                  2018.11.29
chardet                  3.0.4
Click                    7.0
colorama                 0.4.1
coverage                 4.5.2
decorator                4.3.2
defusedxml               0.5.0
docutils                 0.14
dparse                   0.4.1
entrypoints              0.3
flake8                   3.7.5
funcsigs                 1.0.2
gitdb2                   2.0.5
GitPython                2.1.11
httpretty                0.9.6
idna                     2.8
imagesize                1.1.0
ipykernel                5.1.0
ipython                  7.2.0
ipython-genutils         0.2.0
ipywidgets               7.4.2
jedi                     0.13.2
Jinja2                   2.10
jsonschema               2.6.0
jupyter                  1.0.0
jupyter-client           5.2.4
jupyter-console          6.0.0
jupyter-core             4.4.0
linecache2               1.0.0
lxml                     4.3.1
MarkupSafe               1.1.0
mccabe                   0.6.1
mistune                  0.8.4
mock                     2.0.0
more-itertools           5.0.0
nbconvert                5.4.1
nbformat                 4.4.0
notebook                 5.7.4
packaging                19.0
pandocfilters            1.4.2
parso                    0.3.3
pbr                      5.1.2
pickleshare              0.7.5
pip                      19.0.2
pkginfo                  1.5.0.1
pluggy                   0.8.1
ply                      3.11
prometheus-client        0.5.0
prompt-toolkit           2.0.8
py                       1.7.0
pycodestyle              2.5.0
pyflakes                 2.1.0
Pygments                 2.3.1
pyparsing                2.3.1
pytest                   4.2.0
pytest-cov               2.5.1
python-dateutil          2.8.0
pytz                     2018.9
pywbem                   0.12.1.dev228 c:\users\kscho\dev\pywbem3wintest\pywbem
pywinpty                 0.5.5
PyYAML                   3.13
pyzmq                    17.1.2
qtconsole                4.4.3
readme-renderer          24.0
requests                 2.21.0
requests-toolbelt        0.9.1
safety                   1.8.5
Send2Trash               1.5.0
setuptools               40.8.0
six                      1.12.0
smmap2                   2.0.5
snowballstemmer          1.2.1
Sphinx                   1.8.4
sphinx-git               10.1.1
sphinxcontrib-websupport 1.1.0
terminado                0.8.1
testfixtures             5.4.0
testpath                 0.4.2
tornado                  5.1.1
tqdm                     4.31.0
traceback2               1.4.0
traitlets                4.3.2
twine                    1.12.1
unittest2                1.1.0
urllib3                  1.24.1
wcwidth                  0.1.7
webencodings             0.5.1
wheel                    0.32.3
widgetsnbextension       3.4.2
yamlordereddictloader    0.4.0

**Comment by andy-maier** [comment]
Karl, on not executing anything when running `make test`:

According to your output, it does execute something, and to me it looks like it enters a new level of command processor, as if it would ignore the /c flag.

What is the result of `make test -n`?

It should be something like:
```
(pywbem27) C:\Users\Andi\Projects\pywbem\repos\pywbem>make test -n
echo "makefile: Creating the LEX/YACC table modules"
cmd /c del /f /q pywbem\\mofparsetab.py* pywbem\\moflextab.py*
python -c 'from pywbem import mof_compiler; mof_compiler._build(verbose=True)'
echo "makefile: Done creating the LEX/YACC table modules: pywbem/mofparsetab.py pywbem/moflextab.py"
echo "makefile: Creating the LEX/YACC table modules"
cmd /c del /f /q pywbem\\mofparsetab.py* pywbem\\moflextab.py*
python -c 'from pywbem import mof_compiler; mof_compiler._build(verbose=True)'
echo "makefile: Done creating the LEX/YACC table modules: pywbem/mofparsetab.py pywbem/moflextab.py"
echo "makefile: Running unit and function tests"
py.test --color=yes --cov pywbem --cov pywbem_mock  --cov-config coveragerc   tests/unittest tests/functiontest -s
echo "makefile: Done running tests"
```

**Comment by andy-maier** [comment]
On failing testcases: Under python 3.4, `make test` only fails on test_wbem_cli.py (with `ImportError: No module named ply`) and succeeds on all others.

**Comment by andy-maier** [comment]
Karl, I have updated the PR with some more fixes (Using /d option of cmd to avoid registry-based init code, improving dependencies, suppressing more builtin rules).

Please try the `make test` again, after `make clobber install`.

**Comment by KSchopmeyer** [comment]
Results of test monday morning:

1. make develop, make check worked.

2. make test fails:

a. Runs only Creating LEX\YACC tables modules and then nothing more. See below.

b. Tried running just the pytest part without the coverage components and warnings component frm the cmd line. Reduced running tests to just the py.test itself and found all tests run except for:

   i test_cim_xml.py
  ii. test_cim_obj.py

Specifically xmllint could not be found for tests and it is a part of both of the above tests.  The output file was about 15 mb so not uploading that one but the xmllint not found appears to be the bulk of the problem.

Sadly, we have found another discontinuity between windows and Linux. While xmllint is easily supported on linux, mac, it is not a standard install for windows.  There is a faux version available from google but apparently the real version is available from www.zlatkovic.com. While I have a fairly complete but old set of linux stuff ported to windows, I do not have xmllint.   Apparently you can get the windows builds from his site and then download the bins into a local space and it may run.

We have two choices I think:

a. Try to use the downloads from zlatkovic
b. Bypass tests with xmllint in window

cim_xml_str = b'<IRETURNVALUE/>', root_elem_name = None

    def validate_cim_xml(cim_xml_str, root_elem_name=None):
        """
        Validate a CIM-XML string against the CIM-XML DTD, optionally
        requiring a particular XML root element.

        If the validation succeeds, the function returns. Otherwise,
        `CIMXMLValidationError` is raised and its exception message is the
        (possible multi-line) output of the `xmllint` command.

        Parameters:

          cim_xml_str (string): CIM-XML string to be validated.

          root_elem_name (string): Name of XML element that is expected as the root
            element in the CIM-XML string to be validated.
            `None` means no checking for a particular root element is performed.

        Raises:

          CIMXMLValidationError: CIM-XML validation error
        """

        # The DOCTYPE instruction needs the DTD file with forward slashes.
        # Also, the xmllint used on Windows requires forward slashes and complains
        # with "Could not parse DTD tests\dtd\DSP0203_2.3.1.dtd" if invoked
        # with backslashes.
        dtd_file_fw = DTD_FILE.replace('\\', '/')

        # Make sure the validator checks the specified root element, if any
        if root_elem_name is not None:
            cim_xml_str = u'<!DOCTYPE {0} SYSTEM "{1}">\n{2}'. \
                format(root_elem_name, dtd_file_fw, cim_xml_str)
            xmllint_cmd = 'xmllint --valid --noout -'
        else:
            xmllint_cmd = 'xmllint --dtdvalid {0} --noout -'.format(dtd_file_fw)

        p = Popen(xmllint_cmd, stdout=PIPE, stderr=STDOUT, stdin=PIPE, shell=True)

        cim_xml_str = _ensure_bytes(cim_xml_str)
        p.stdin.write(cim_xml_str)
        p.stdin.close()

        status = p.wait()
        if status != 0:
            out_lines = p.stdout.readlines()
            output = _ensure_unicode(b'\n'.join(out_lines))
>           raise CIMXMLValidationError(output)
E           tests.unittest.utils.validate.CIMXMLValidationError: 'xmllint' is not recognized as an internal or external command,
E
E           operable program or batch file.

tests\unittest\utils\validate.py:132: CIMXMLValidationError

During handling of the above exception, another exception occurred:

self = <tests.unittest.pywbem.test_cim_xml.IReturnValue testMethod=test_all>

    def test_all(self):
        """Loop over xml to execute tests"""

        for i in range(0, len(self.xml)):

            xml_node = self.xml[i]
            act_xml_str = xml_node.toxml()

            # Test that the XML fragments pass validation against CIM-XML DTD
>           self.validate(act_xml_str)

tests\unittest\pywbem\test_cim_xml.py:363:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

xml = '<IRETURNVALUE/>', expectedResult = 0

    @staticmethod
    def validate(xml, expectedResult=0):
        # pylint: disable=unused-argument
        """xml is a string with the CIM-XML."""

        try:
            validate_cim_xml(xml)
        except CIMXMLValidationError as exc:
            raise AssertionError(
                "DTD validation of CIM-XML failed:\n"
                "{0}\n"
                "CIM-XML string:\n"
                "{1}".
>               format(exc, xml))
E           AssertionError: DTD validation of CIM-XML failed:
E           'xmllint' is not recognized as an internal or external command,
E
ERROR: Failed to generate report: No data to report.


```
(pywbem3wintest) C:\Users\kscho\dev\pywbem3wintest\pywbem>make test
make[8]: Entering directory `C:/Users/kscho/dev/pywbem3wintest/pywbem'
makefile: Creating the LEX/YACC table modules
cmd /d /c del /f /q pywbem\\mofparsetab.py* pywbem\\moflextab.py*
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

(pywbem3wintest) C:\Users\kscho\dev\pywbem3wintest\pywbem>py.test --color=yes --cov $(package_name) --cov $(mock_package_name) $(coverage_report) --cov-config coveragerc $(pytest_warnings_opts) $(pytest_opts) tests/unittest tests/functiontest -s | tee maketestout.txt
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: C:\Users\kscho\dev\pywbem3wintest\pywbem, inifile:
plugins: cov-2.5.1

======================== no tests ran in 0.05 seconds =========================ERROR: file not found: $(coverage_report)

```

**Comment by andy-maier** [comment]
On xmllint: I found that Chocolatey can install xmllint very nicely, without  having to figure out all the dependent packages:

`choco install xsltproc`

contains the xmllint command.

**Comment by andy-maier** [comment]
On `make test` only running MOF table generation:

So the `/d` option did not help. The two lines shown in your output:
```
cmd /d /c del /f /q pywbem\\mofparsetab.py* pywbem\\moflextab.py*
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.
```
seem to indicate that this is opening an interactive command prompt.

**Comment by KSchopmeyer** [comment]
Found issue that was causing make to hang in windows with things like *.pyc within cmd call.  Appears to be the git that was on this system Git For Windows that includes a bash and sh.exe.  Removed that complete git and replaced it with choco install git and the cmd calls within windows no longer hang.  Tested make install check build OK.

Problems with make build: The problems are:

1. the _check_version prerequisite fails.

2. Removed that and it tries to execute line in makefile with xargs. No xargs in windows.

**Comment by andy-maier** [comment]
Karl, the latest update has several fixes (see its commit message).

It should now solve all issues, except that it does not automatically install make or xmllint on Windows.

**Comment by andy-maier** [comment]
The last update now automatically installs xmllint as part of `make develop`.

**Comment by andy-maier** [comment]
Here is our list of environments for Windows that we would support, document, test locally, and ideally run in Appveyor:

In CMD shell (used for terminal session and used as a shell by make, with Python installed to Windows from python.org):
  * Chocolatey packages
  • Probably: MSYS2

In bash shell (used for terminal session and used as a shell by make)
  • Linux subsystem of Windows 10 (TBD: Does it have a Python?)
  * CygWin (incl. its Python)

**Comment by andy-maier** [comment]
The latest update also bringsthe Installation section of the documentation in sync with the code.

**Comment by andy-maier** [comment]
Please test the installation and the setup of the development environment on Windows.

**Comment by andy-maier** [comment]
I added retry support for choco installations, by using the "appveyor-retry" command. It retries 3 times (including the original attempt), and has no sleep time between retries.

In the Appveyor run for this latest update to the PR we had 3/3 successes without retries.

I rebased the "manual-ci-run" on this PR, and the Appveyor run there now has 32 jobs, and I already left out some combinations. In the recent run based on the latest update to this PR, its 32 jobs succeed or failed as follows:
- 30 jobs succeeded without any retries
- 1 job succeeded after 1 retry (https://ci.appveyor.com/project/andy-maier/pywbem/builds/22444564/job/36aslgho3q4ub5b0)
- 1 job failed after exceeding the retry limit (https://ci.appveyor.com/project/andy-maier/pywbem/builds/22444564/job/mq8rl6lulivr1kg7)

So this got better than without the retries (I saw 5 jobs failing out of the 32, before the last update), but it is not yet safe enough for automatic runs. Of course, if it happens rarely enough, we can rerun the failing jobs (Appveyor offers that button once the whole build is finished).

**Comment by andy-maier** [comment]
In our call today, Karl and I agreed to merge this one ot make progress. We would keep the retry.bat script.

**Pull request merged**
