### PR TITLE
Cleanup of flake8 and pylint issues

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Ready for review.  I may have one more change today.

Cleans up a number of flake8 issues. This reduces the flake8 count from
about 200 to about 50 messages.

Currently the flake8 message summary is as follows:
```
3     E131 continuation line unaligned for hanging indent
33    E501 line too long (115 > 80 characters)
1     F401 '._version.__version__' imported but unused
8     F821 undefined name 'basestring'
1     F841 local variable 'insts_enum' is assigned to but never used
2     W601 .has_key() is deprecated, use 'in'
```
the E501 cover two issues:

1. A bunch of long lines in cim_operations.py in the table but we do not want to exclude this from the whole module.  flake8 has an issue with trying to ignore selected groups of code and further these are all in a comment and that causes further issues for flake8 since its only ignore mechanisms are:

    ignore this line: # noqa: Fxxx

    ignore for this file # flake8: noqa: Fxxx

2. E131 - in setup.py in a very complex statement 

3. F841 - An issue that I am in process of fixing

4. W601 - I think this is our has_key rather than python

With all of the warnings turned off the flake 8 message summary is:
```
55    E127 continuation line over-indented for visual indent
39    E128 continuation line under-indented for visual indent
3     E131 continuation line unaligned for hanging indent
108   E261 at least two spaces before inline comment
107   E265 block comment should start with '# '
485   E302 expected 2 blank lines, found 1
115   E303 too many blank lines (2)
13    E402 module level import not at top of file
85    E501 line too long (115 > 80 characters)
454   E502 the backslash is redundant between brackets
14    F401 '.cim_types.*' imported but unused
12    F403 'from .cim_types import *' used; unable to detect undefined names
2     F821 undefined name 'ResourceWarning'
6     F841 local variable 'dummy_type_obj' is assigned to but never used
15    W391 blank line at end of file
2     W601 .has_key() is deprecated, use 'in'
```

### CODE REVIEW

**Comment by andy-maier** [comment]
So far, +1.
Please post any further changes as a separate commit.

**Comment by KSchopmeyer** [comment]
+1  Sounds good

**Comment by andy-maier** [comment]
I'm waiting for more updates then.

**Comment by KSchopmeyer** [comment]
No. Lets commit this and then continue.

**Pull request merged**
