### PR TITLE
WITHDRAWN Fixes #691 and #569: log of cim operations api and http messages with wbemcli extended to use log

### LINKED ISSUE #691: Add ability to log selected data on operations
Today the user can get back some information after a wbem operations (cim_operation method) has executed including 1. last request/reply, last time, size.

However, all of this information is lost when the user initiates the next operation.  It would be logical to add the functionality to selectively log this information.  Since Python provides a complete and extensively used logging tool, it would be logical to extend pywbem to actually provide the logging within pywbem itself.

Add a mechanism to enable python logging of selected data on operations.  It appears that the two areas of primary interest for logging are:

1. HTTP requests and responses - This would log the http for all requests and responses
2. CIM Operation method calls and responses. -This would log the parameters of each of the wbemconnection methods that result in wbem requests and also the responses at the level they are returned to the user

Since this can represent a lot of data we need to sort out a scheme that allows the user to be very selective in what is logged.

Questions for the design:

1. Log things as they happen.  Thus one log each for pywbemcall, httpsent, rttp_response, pywbem_response vs. log the complete results as a single log entry.  I propose that we log as things happen so that complete logging on a single request/response would be 4 log entries. 

CONCLUSION: We agree that we log as they occur

2. Log with just a single variable on/off vs. ability to enable log separately for the request/response info vs the http info.  I propose that we at least provide ability to enable the request/response level from the http level logging.
It may be logical to set upper size on responses although we never did with Pegasus and it worked well.  It would be good to have a switch to include or exclude the payload.

3. Selectively log certain methods - Right now this seems like overkill.

4. Attach the logging to the record mechanism since it is already gathering information  for each operation or create a parallel logger. I am prototyping using the recorder but there are alternatives such as decorators that would execute the logging.

This replaces part of issue # 569 that set requirement for testing wemcli and cmdline mof compiler

### PR DESCRIPTION
**Pull request by KSchopmeyer**
**Based on Andy's comment, I am withdrawing this PR and submitting pieces of work as separate prs.**  I will document that list of new PRs as it is submitted.

Logger function added to recorder.  This is no longer a prototype.  However, it functionally complete now but has some issues (see Not Done).

I am keeping this WIP for another day or so while I work out the not done list below.

Includes:
1. New LogOperationRecorder class in recorder logs operations request/responses and http request/responses.  Note that logging for each can be defined separately so that each can have a destination (file, stderr), log_level(debug, etc) and detail level (how much information is output)
2. Addition of PywbemLoggers class in _logging that manages loggers creating new named loggers and keeping the information that logging cannot handle (detail level). Includes parsing of the command line parameter for logging so wbemcli and pywbemtools do not have to do this separately.
3. Add new script test for wbemcli (test_wbemcli.py).  Only includes a few tests today but new tests can be easily added.
4. Extend wbemconnection to add new constructor (enable_logging) that is a boolean.  When this is created, the LogOperationRecorder gets the detail level info from PywbemLoggers by logger name.

Not done:
1. The tests in test_logging and test_wbemcli are incomplete. COMMENT: Move any new tests forward to new issue
2. Some of the new code in _logging.py is a hack and just needs refactoring. In fact, I have only lightly tested the final result. Cleaned up. **Done**
3. There is no documentation on the logging (or for that matter the statistics) in the documentation. COMMENT: Create new issue
4. I left the input parameters in their original order for the moment (destination:detail:log_level rather than Andy's proposal for different order. We should discuss the levels of detail (min, all) right now and exactly what they mean.  The structure is in place so we can manage this detail level as we want to.  Right now detail output 1000 char and all outputs everything.  Maybe a hdrs_only or something but not sure exactly what that means.   COMMENT: Create new issue
5. Not displaying enough in wbemcli when logger enabled. Just says logging=true no info about components, etc. Minor. COMMENT: Create new issue 
6. Only outputs logger or test recorder, not both.  I know how to extend to do both but wanted to get this much running first.   COMMENT: Create new issue
7. I need to review logging of the wbemconnection itself since it is NOT linked to the other log outputs. The logical way to do this might to be to set a counter that increments for each new connection and this counter also is set into the ops and http logs.   COMMENT: Create new issue

DISCUSSION:
1. Do we really need to be able to do both log and test recorder at the same time.
2. Do we need to link the ops/http logs to the connection.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
```
)$ cat wbemcli.log
2017-06-21 08:31:36,182-pywbem.ops-DEBUG-http://localhost(stats_enabled=False, use_pull_operations=None, timeout=None, default_namespace='root/cimv2')
2017-06-21 08:31:38,277-pywbem.ops-DEBUG-GetClass(PropertyList=None, ClassName='cim_managedelement', LocalOnly=None, IncludeClassOrigin=None, IncludeQualifiers=None, namespace=None)
2017-06-21 08:31:38,281-pywbem.http-DEBUG-HTTP Request POST http://localhost /cimom 11
Content-length:'374'
CIMOperation:'MethodCall'
CIMObject:'root/cimv2'
CIMMethod:'GetClass'
PegasusAuthorization:'Local "kschopmeyer"'
Content-type:'application/xml; charset="utf-8"'
b'<?xml version="1.0" encoding="utf-8" ?>\n<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="cim_managedelement"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>'
2017-06-21 08:31:38,289-pywbem.ops-DEBUG-GetClass: Exception: TypeError('non-empty format string passed to object.__format__',)...
2017-06-21 08:32:48,114-pywbem.ops-DEBUG-http://localhost(stats_enabled=False, timeout=None, default_namespace='root/cimv2', use_pull_operations=None)
2017-06-21 08:32:50,925-pywbem.ops-DEBUG-GetClass(IncludeClassOrigin=None, IncludeQualifiers=None, PropertyList=None, namespace=None, LocalOnly=None, ClassName='cim_managedelement')
2017-06-21 08:32:50,929-pywbem.http-DEBUG-HTTP Request POST http://localhost /cimom 11
CIMOperation:u'MethodCall'
Content-length:'374'
CIMMethod:u'GetClass'
PegasusAuthorization:'Local "kschopmeyer"'
CIMObject:u'root/cimv2'
Content-type:'application/xml; charset="utf-8"'
<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetClass"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="cim_managedelement"/></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
2017-06-21 08:32:50,938-pywbem.http-DEBUG-HTTP Response 200 OK 11
cimoperation:'MethodResponse'
content-length:'0000004187'
content-type:'application/xml; charset=utf-8'
<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
<MESSAGE ID="1001" PROTOCOLVERSION="1.0">
<SIMPLERSP>
<IMETHODRESPONSE NAME="GetClass">
<IRETURNVALUE>
<CLASS NAME="CIM_ManagedElement" >
<QUALIFIER NAME="Abstract" TYPE="boolean" TOSUBCLASS="false">
<VALUE>TRUE</VALUE>
</QUALIFIER>
<QUALIFIER NAME="Version" TYPE="string" TOSUBCLASS="false" TRANSLATABLE="true">
<VALUE>2.19.0</VALUE>
</QUALIFIER>
<QUALIFIER NAME="UMLPackagePath" TYPE="string">
<VALUE>CIM::Core::CoreElements</VALUE>
</QUALIFIER>
<QUALIFIER NAME="Description" TYPE="string" TRANSLATABLE="true">
<VALUE>ManagedElement is an abstract class that provides a common superclass (or top of the inheritance tree) for the non-association classes in the CIM Schema.</VALUE>
</QUALIFIER>
<PROPERTY NAME="InstanceID"  TYPE="string">
<QUALIFIER NAME="Description" TYPE="string" TRANSLATABLE="true">
<VALUE>InstanceID is an optional property that may be used to opaquely and uniquely identify an instance of this cla...
2017-06-21 08:32:50,945-pywbem.ops-DEBUG-GetClass: Return: CIMClass(classname=u'CIM_ManagedElement', superclass=None, properties=NocaseDict({u'InstanceID': CIMProperty(name=u'InstanceID', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=None, qualifiers=NocaseDict({u'Description': CIMQualifier(name=u'Description', value=u'InstanceID is an optional property that may be used to opaquely and uniquely identify an instance of this class within the scope of the instantiating Namespace. Various subclasses of this class may override this property to make it required, or a key. Such subclasses may also modify the preferred algorithms for ensuring uniqueness that are defined below.\nTo ensure uniqueness within the NameSpace, the value of InstanceID should be constructed using the following "preferred" algorithm: \n<OrgID>:<LocalID> \nWhere <OrgID> and <LocalID> are separated by a colon (:), and where <OrgID> must include a copyrighted, trademarked, or otherwise unique ...

```

**Comment by KSchopmeyer** [comment]
```
  -l log_spec[,logspec], --log log_spec[,logspec]
                        Where log_spec is the form:
                         COMP=DEST:[DETAIL]:[LEVEL] where:
                           COMP: [ops|http|all] Component name
                           DEST: [file|stderr|none] Destination for component
                           DETAIL: [all|min] Detail Level to log
                           LEVEL: [error|warning|info|debug] Log level
                        (Defaults: COMP=all DEST=none, LEVEL=all).

```

comp=level,detail,dest

**Comment by KSchopmeyer** [comment]
Andy noted that because this is already a big pr, we should no nothing more with this but get it into the code and file issues on any outstanding work. That includes: 1. connecting wbemconnection log entry to ops and http logs, and outputting to both recorders at the same time.

Karl will perform only code cleanup and finish tests for this pr.

**Comment by KSchopmeyer** [comment]
The tests failed with the following from test_wbemcli.py

```
        if not expected_stderr:
            self.assertEqual(std_err, "",
                             '%s stderr not empty. returned %s'
>                            % (test_name, std_err))
E           AssertionError: test_timeout stderr not empty. returned /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coverage/config.py:29: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.

E             return configparser.RawConfigParser.read(self, filename, **kwargs)
```

It also generated the following warning:
testsuite/test_wbemcli.py:117: AssertionError
```
============================ pytest-warning summary ============================

WC1 /home/travis/build/pywbem/pywbem/testsuite/test_recorder.py cannot collect test class 'TestClientRecorder' because it has a __init__ constructor


```

The first issue is a test in test_wbemcli.py where we test the stderr return for empty.  We should be protecting against this because the command we actually issue is:

export PYTHONWARNINGS="" && %s

where the %s is the complete wbemcli command string.  Therefore, I am not yet sure why that warning was issued.

**Comment by KSchopmeyer** [comment]
We need to fix the test problem and then we can consider committing.

**Comment by KSchopmeyer** [comment]
I thought that we were installing cygwin.  The following error generated from test_wbemcli.py indicates that the shell cannot recognize export as a valid operation which tells me that there is an issue with cygwin.

```
        if test_params.expected_exitcode is not None:
            self.assertEqual(exitcode, test_params.expected_exitcode,
                             ('Test %s: Unexpected ExitCode Err. '
                              'Expected %s: cmd="%s": '
                              'exitcode %s: stderr=%s' %
                              (test_name, test_params.expected_exitcode,
                               command,
>                              exitcode, std_err)))
E           AssertionError: Test test_timeout: Unexpected ExitCode Err. Expected 0: cmd="export PYTHONWARNINGS="" && wbemcli http://blah -t 10 -s C:\projects\pywbem\testsuite\wbemcli_quit_script.py": exitcode 1: stderr='export' is not recognized as an internal or external command,
E           operable program or batch file.
testsuite\test_wbemcli.py:144: AssertionError
```

**Comment by KSchopmeyer** [comment]
The good news is that we are down to one apveyor issue, the exit code from wbemcli upon an error.
In testing on linux, I found that a particular bad syntax input generated code 2. On Windows it exits with zero.

```
        if test_params.expected_exitcode is not None:
            self.assertEqual(exitcode, test_params.expected_exitcode,
                             ('Test %s: Unexpected ExitCode Err. '
                              'Expected %s: cmd="%s": '
                              'exitcode %s: stderr=%s' %
                              (test_name, test_params.expected_exitcode,
                               cmd,
>                              exitcode, std_err)))
E           AssertionError: Test test_error_param: Unexpected ExitCode Err. Expected 2: cmd="wbemcli.bat http://blah --log -s C:/projects/pywbem/testsuite/wbemcli_quit_script.py": exitcode 0: stderr=usage: wbemcli [options] server
E           wbemcli: error: argument -l/--log: expected one argument
testsuite\test_wbemcli.py:146: AssertionError

Questions:

1. I am using wbemcli.bat.  I was fighting finding wbemcli in windows so tried using the bat file.  Strangely, this worked.

```

**Comment by KSchopmeyer** [comment]
+1 but feel free to tell me to fix code. :-)

**Comment by andy-maier** [comment]
Please resolve the conflict that resulted from merging PR #720.

**Comment by KSchopmeyer** [comment]
Based on the comment about too many changes, I see no alternative but to withdraw this pr completely and try to redo it in pieces.

I will first submit the incidental components (errors found elsewhere that impact getting this pr to work and then try to figure out how to break up the basic work on logging into pieces.)  At this point I do not see me making any real coding changes, just changes to make a number of smaller PRs from this one.

**Comment by andy-maier** [comment]
Please close this PR once you have everything from it in other PRs.

**Comment by KSchopmeyer** [comment]
Closing this pr as obsolete. It was replaced by 3 others representating the 3 components of the logging functionality.

**Comment by KSchopmeyer** [comment]
This is obsolete and withdrawn. Close it

**Pull request closed without merging**
