### PR TITLE
Improved and fixed documentation.

### PR DESCRIPTION
**Pull request by andy-maier**
This PR makes a number of changes in the documentation, that I think are needed before we release v0.9.0.

Ready for review and merge.

Details:
- Moved "Package version" chapter from "WBEM client library API" section into
  "Introduction" section.
- Fixed missing and incorrect anchors in `client.rst`.
- Refactored package docu (module docstring in `__init.py__`), by moving
  (and improving) information about namespaces and external symbols into a new
  chapter "Python namespaces" in the "Introduction" section, and by moving the
  introduction of the chapters to the WBEM client library API into `client.rst`,
  adding the entry for "Security Considerations".
- Improved the introduction text of the "WBEM server API", "WBEM listener
  API", and "MOF compiler API" chapters.
- For `ValueMapping`, corrected the statement that bidirectional translation of
  values is supported, to state that only translation from the actual value
  to the Values value is supported.
- Added anchors for the sections within the "WBEM server API" and "WBEM listener
  API" chapters.
- Moved the "Configuration" chapter as a section into the "Introduction"
  chapter, and improved it.
- Stated that config variables should be used from the `pywbem` namespace (not
  from `pywbem.config`).
- Fixed a few indentation issues in changes.rst.
- Added a reference to "WBEM Standards", and referenced it from the package
  intro.
- Some more minor improvements.
- Included the member functions and properties of `MOFParseError` into the
  MOF compiler API (they had been forgotten so far), and improved their
  documentation.
- Fixed formatting issues in WBEM listener API and WBEM server API.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
index.rst.  You added 

"This is used for all kinds of systems management tasks that are supported by
the system running the WBEM server"  In the paragraph starting with "A WBEM..."

Not sure that sentence really contributes anything.

intro.rst.  Thini the word pywbem is inconsistently marked.  Not in the first paragraph but quoted in some subsequent paragraphs with **

Those are all minor so in general I vote +1 for this change

**Comment by andy-maier** [comment]
On the sentence "This is used..:": I wanted to say something about its purpose for people that don't know what it is. Can you come up with a better sentence? We have that sentence in a number of places now.

On the markup for the term "pywbem": In adition to inconsistent markup, there is both "pywbem" and "PyWBEM". We have come from using PyWBEM for the project and pywbem for the package. Is that a distinction we should continue to have?

**Comment by andy-maier** [comment]
We agreed on:
- We use "PyWBEM" for the set of PyWBEM projects (client, server, providers, yawn), and "pywbem" for the client. The "PyWEM server" becomes "Python server".
- Clean up markup in pywbem docs.
- Karl will think about a better wording for the offending sentence.

**Comment by andy-maier** [comment]
The last commit addresses the spelling and markup issues for the term 'pywbem'.

ToDos:
- Karl: Come up with a better way of explaining what WBEM/CIM does.
- Andy: Update github.io pages for the naming.

**Comment by KSchopmeyer** [comment]
"This is used for all kinds of systems management tasks that are supported by
the system running the WBEM server" In the paragraph starting with

The CIM/WBEM infrastructure is used for a wide variety of systems management tasks supported by systems running WBEM Servers

Maybe that is a little better.

**Comment by andy-maier** [comment]
Applied that proposal, plus some more minor docs changes. See last commit.
+1

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
