### PR TITLE
fixes #1276 mock repository_display() unicode issue

### LINKED ISSUE #1276: pywbem_mock  _wbemconnection.py outputs bytes
In python 3 the uprint method outputs bytes and not unicode.   The method str.encode produces a byte output not unitocde so that the result is bytes when the terminal output is used.

Python 3 output to terminal

    b'# Namespace root/blah: contains 9 Qualifier Declarations \n'
    b'Qualifier Abstract : boolean = false,\n    Scope(class, association, indication),\n       Flavor(EnableOverride, Restricted);\n'
    b'Qualifier Aggregate : boolean = false,\n    Scope(reference),\n    Flavor(DisableOverride, ToSubclass);\n'

Python 2 output to terminal::

    # Namespace root/blah: contains 9 Qualifier Declarations 

    Qualifier Abstract : boolean = false,
        Scope(class, association, indication),
        Flavor(EnableOverride, Restricted);

    Qualifier Aggregate : boolean = false,
        Scope(reference),
       Flavor(DisableOverride, ToSubclass);

Output to file in python 3 has same issue.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
See commit for details.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
The failure now is with windows and is as follows:

        tst_file_name = 'test_wbemconnection_mock_repo_unicode.txt'
        tst_file = os.path.join(TEST_DIR, tst_file_name)
    
    >       conn.display_repository(dest=tst_file)
    testsuite\test_wbemconnection_mock.py:1216: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    pywbem_mock\_wbemconnection_mock.py:804: in display_repository
    summary=summary, output_format=output_format)
    pywbem_mock\_wbemconnection_mock.py:883: in _display_objects
        _uprint(dest, obj.tomof())
    pywbem_mock\_wbemconnection_mock.py:116: in _uprint
        print(text, file=f)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    self = <encodings.cp1252.IncrementalEncoder object at 0x000000738841DDA0>
    input = 'class CIM_Foo {\\r\\n\\r\\n      [Key ( true ),\\r\\n       Description ( "\u212b 
     \u0420\u043e\u0441\u0441\u0438\u044f\xe0 voil\xe0" )]\\r\\n   string InstanceID;\\r\\n\\r\\n};\\r\\n'
        final = False
        def encode(self, input, final=False):
    >       return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    E       UnicodeEncodeError: 'charmap' codec can't encode character '\u212b' in position 63: character 
    maps to <undefined>
    .tox\pywin\lib\encodings\cp1252.py:19: UnicodeEncodeError
    ----------- coverage: platform win32, python 3.6.5-final-0 -----------

**Comment by andy-maier** [comment]
I fixed it (and rebased it to resolve a merge conflict).

There were two issues:
- The use of the Angstrom character was not correctly Python-escaped, but some form of bytes (probably in UTF-8), which is not legal in a unicode string. Fixed that by changing it to a Python unicode escape.
-  The _uprint method was called multiple times with a byte string, despite its documented precondition of unicode string. Found that by adding an assert, and fixed it by converting byte strings to unicode.

If you continue working on this branch, you need to delete it locally and check it out again.

**Comment by KSchopmeyer** [comment]
Thanks. Sometimes my mind just seems to get all tangled up. I cleaned up the print statements, marked the test that is just a display tool as skip and fixed several pylint issues with indenting, etc.

As far as I am concerned we can commit this one.

**Comment by KSchopmeyer** [comment]
If it passes the tests

**Pull request merged**
