### PR TITLE
Memory inefficiency with DOM #498: Add sax parser. Replaced by by pr 562

### PR DESCRIPTION
**Pull request by willspearman**
Added SAX handler class that gets called instead of the DOM recursive parser. Added unit tests that show no regressions with a few sample responses. Feel free to add more examples in _testsuite/tupletree_ok_.

Karl cleaned up the code for this and created a new pr.  Please review the new pr.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Reports back the following error on Python 2.6 and only 2.6

./wbemcli --help >docs/wbemcli.help.txt

Traceback (most recent call last):

  File "./wbemcli", line 56, in <module>

    from pywbem import WBEMConnection

  File "/home/travis/build/pywbem/pywbem/pywbem/__init__.py", line 37, in <module>

    from .cim_operations import *

  File "/home/travis/build/pywbem/pywbem/pywbem/cim_operations.py", line 123, in <module>

    from .tupleparse import parse_cim

  File "/home/travis/build/pywbem/pywbem/pywbem/tupleparse.py", line 89, in <module>

    from .tupletree import xml_to_tupletree

  File "/home/travis/build/pywbem/pywbem/pywbem/tupletree.py", line 92

    element = (name, {k: v for k, v in attrs.items()},

                             ^

SyntaxError: invalid syntax

make: *** [docs/wbemcli.help.txt] Error 1

**Comment by KSchopmeyer** [comment]
I talked to will and he will make fix Monday.

**Comment by KSchopmeyer** [comment]
Now we are getting failures with Python 3.4 as follows:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pywbem/tupletree.py:166: in xml_to_tupletree_sax

    xml.sax.parseString(xml_string, handler, None)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

string = '<?xml version="1.0" encoding="utf-8" ?>\n<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1...\n</PROPERTY>\n</INSTANCE>\n</VALUE.OBJECTWITHPATH>\n\n</IRETURNVALUE></IMETHODRESPONSE></SIMPLERSP></MESSAGE></CIM>\n'

handler = <pywbem.tupletree.CIMContentHandler object at 0x2b1b42fee8d0>

errorHandler = <xml.sax.handler.ErrorHandler object at 0x2b1b42fee0b8>

    def parseString(string, handler, errorHandler=ErrorHandler()):

        from io import BytesIO

    

        if errorHandler is None:

            errorHandler = ErrorHandler()

        parser = make_parser()

        parser.setContentHandler(handler)

        parser.setErrorHandler(errorHandler)

    

        inpsrc = InputSource()

>       inpsrc.setByteStream(BytesIO(string))

E       TypeError: 'str' does not support the buffer interface

/opt/python/3.4.4/lib/python3.4/xml/sax/__init__.py:45: TypeError

__________________ TestTupleTreeError.test_to_tupletree_error __________________

self = <test_tupletree.TestTupleTreeError testMethod=test_to_tupletree_error>

    def test_to_tupletree_error(self):

        """SAX parsing generates errors."""

        filename = os.path.join(self.data_dir, 'Associators_error.xml')

        with open(filename, 'r') as fh:

            xml_str = fh.read()

            self.assertRaises(xml.sax.SAXParseException,

>                             tupletree.xml_to_tupletree_sax, xml_str)

testsuite/test_tupletree.py:151: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pywbem/tupletree.py:166: in xml_to_tupletree_sax

    xml.sax.parseString(xml_string, handler, None)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def parseString(string, handler, errorHandler=ErrorHandler()):

        from io import BytesIO

    

        if errorHandler is None:

            errorHandler = ErrorHandler()

        parser = make_parser()

        parser.setContentHandler(handler)

        parser.setErrorHandler(errorHandler)

    

        inpsrc = InputSource()

>       inpsrc.setByteStream(BytesIO(string))

E       TypeError: 'str' does not support the buffer interface

/opt/python/3.4.4/lib/python3.4/xml/sax/__init__.py:45: TypeError

__________________ TestTupleTreeSax.test_xml_to_tupletree_sax __________________

self = <test_tupletree.TestTupleTreeSax testMethod=test_xml_to_tupletree_sax>

    def test_xml_to_tupletree_sax(self):

        """XML to tupletree with SAX is accurate."""

        data_dir = resource_filename(__name__, 'tupletree_ok')

        path = os.path.join(data_dir, 'Associators_StorageVolume_small.xml')

        with open(path, 'r') as fh:

            xml_str = fh.read()

>       tree_sax = tupletree.xml_to_tupletree_sax(xml_str)

testsuite/test_tupletree.py:162: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pywbem/tupletree.py:166: in xml_to_tupletree_sax

    xml.sax.parseString(xml_string, handler, None)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

string = '<?xml version="1.0" encoding="utf-8" ?>\n<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1...\n</PROPERTY>\n</INSTANCE>\n</VALUE.OBJECTWITHPATH>\n\n</IRETURNVALUE></IMETHODRESPONSE></SIMPLERSP></MESSAGE></CIM>\n'

handler = <pywbem.tupletree.CIMContentHandler object at 0x2b1b4302bba8>

errorHandler = <xml.sax.handler.ErrorHandler object at 0x2b1b4302b748>

    def parseString(string, handler, errorHandler=ErrorHandler()):

        from io import BytesIO

    

        if errorHandler is None:

            errorHandler = ErrorHandler()

        parser = make_parser()

        parser.setContentHandler(handler)

        parser.setErrorHandler(errorHandler)

    

        inpsrc = InputSource()

>       inpsrc.setByteStream(BytesIO(string))

E       TypeError: 'str' does not support the buffer interface

```

**Comment by willspearman** [comment]
Yes, I see. I am looking into that right now.

**Comment by willspearman** [comment]
All tests passing now.

**Comment by willspearman** [comment]
Is there anything else for me to do for this?

**Comment by KSchopmeyer** [comment]
Still failing. We cheated you by adding appveyer but it is failing in appveyor.  Also, rebake to latest master to get rid of conflicts

**Comment by willspearman** [comment]
I have rebased my fork's master to fix the conflict. The checks do not appear to be running again and I cannot see the details to see if there are any additional problems.

**Comment by willspearman** [comment]
Fork synced, conflicts removed, all checks passed.

**Comment by KSchopmeyer** [comment]
Feels better doesn't it.

**Comment by KSchopmeyer** [comment]
I am putting together an enumeration performance test today; it will run the pull and non-pull operations over a wide variety of response counts, response instance size, and maxObjectCounts to see what the overall relative performance is.  If I can finish a first version of this today, we can test against the original code and the changes in the pr before committing the pr.

In the mean time I have run this through pywbem 2.7 tests and the run_cimoperations.py tests with only one problem that is probably something in run_cimoperations.py.

Will repeate for pywbem 3 today

**Comment by KSchopmeyer** [comment]
I completed the python 3 tests with no more issues that the python2.  Also created a performance program that tests over a wide variaety of sizes, etc both with pull and non-pull.   I have a bit more work to organize the output but the general result appears to be on a time-to-complete operations there is very little difference between the new parser and the DOM. The results appear to show no real time differences.  Thus,  the DOM implementation:
OrigEnumInsts instancescount=10000  instance_size=10000   time=0:00:18.918779
OrigEnumInsts  instancescount=100000  instance_size=10000  time=0:02:58.373971
and the new implementation produces:
OrigEnumInsts   instancescount=10000  instance_size=10000   time=0:00:18.258165
OrigEnumInsts instancescount=100000   instance_size=10000  time=0:03:34.567565

I have not really done any memory testing.

**Comment by willspearman** [comment]
In the Issue I opened I included a dataset and script that demonstrated large improvements in python2. I would be interested to know if I made some mistake in my setup that artificially inflated the results.

**Comment by KSchopmeyer** [comment]
Will. I was measuring throughput time, not memory usage.  I never expected that much improvement in the overall transaction time.  The xml processing is jut one part of it and the basic processing has not changed (i.e. the tuple parser).  I do expect that this represents a big change in memory usage and will try to create a memory profile test in next day or so.

All we showed is that there is not a big difference in throughput time.

**Comment by KSchopmeyer** [comment]
Since I cannot contribute back to Will's repository, I have created a new pr after rebasing his changes to our master and cleaning up some editorial issues. uploaded this as pr 562.

**Pull request closed without merging**
