### PR TITLE
Release 0.8.3

### PR DESCRIPTION
**Pull request by andy-maier**
The PR releases PyWBEM v0.8.3.
Changes are described in the `pywbem/NEWS` file.
Please review.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by KSchopmeyer** [comment]
Andy. Sort of lost the train here but I tried running this as a test and it does pass the tests on linux.  However, got a bunch of warnngs I have never seen before from wbemcli.py: Sorry, only capture the last couple.  Thes issues did not show up when run against python3.

They showed up as warnings and it passed all tests but that warning output is new to me.

+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 978, in pywbem.cim_xml.PARAMETER
|   Warning: Line 986: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1016, in pywbem.cim_xml.PARAMETER_ARRAY
|   Warning: Line 1024: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1038, in pywbem.cim_xml.PARAMETER_REFARRAY
|   Warning: Line 1046: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 997, in pywbem.cim_xml.PARAMETER_REFERENCE
|   Warning: Line 1005: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 808, in pywbem.cim_xml.PROPERTY
|   Warning: Line 822: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 866, in pywbem.cim_xml.PROPERTY_ARRAY
|   Warning: Line 880: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 912, in pywbem.cim_xml.PROPERTY_REFERENCE
|   Warning: Line 922: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 762, in pywbem.cim_xml.QUALIFIER
|   Warning: Line 775: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 282, in pywbem.cim_xml.QUALIFIER_DECLARATION
|   Warning: Line 289: Unexpected indentation.
|   
  [..........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1471, in pywbem.cim_xml.RETURNVALUE
|   Warning: Line 1478: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 327, in pywbem.cim_xml.SCOPE
|   Warning: Line 335: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1518, in pywbem.cim_xml.SIMPLEREQACK
|   Warning: Line 1527: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1061, in pywbem.cim_xml.TABLECELL_DECLARATION
|   Warning: Line 1069: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_xml.py,
| line 1079, in pywbem.cim_xml.TABLECELL_REFERENCE
|   Warning: Line 1087: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| cimxml_parse.py, line 23, in pywbem.cimxml_parse
|   Warning: Line 27: Unknown target name: "parse".
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| cimxml_parse.py, line 1015, in pywbem.cimxml_parse.parse_any
|   Warning: Line 1016: Unknown target name: "parse".
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| cimxml_parse.py, line 404, in pywbem.cimxml_parse.parse_instancename
|   Warning: Lines 407, 409: Unexpected indentation.
|   Warning: Line 410: Unexpected possible title overline or 
|            transition.
|            Treating it as ordinary text because it's so short.
|   Warning: Line 410: Block quote ends without a blank line; 
|            unexpected unindent.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| cimxml_parse.py, line 322, in pywbem.cimxml_parse.parse_namespace
|   Warning: Lines 325, 327: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| cimxml_parse.py, line 238, in 
| pywbem.cimxml_parse.parse_namespacepath
|   Warning: Line 241: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| mof_compiler.py, line 1640, in 
| pywbem.mof_compiler.MOFCompiler.__init__
|   Warning: Lines 1645, 1663: Unexpected indentation.
|   Warning: Line 1659: Block quote ends without a blank line; 
|            unexpected unindent.
|   Warning: Line 1661: Definition list ends without a blank line; 
|            unexpected unindent.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| mof_compiler.py, line 1680, in 
| pywbem.mof_compiler.MOFCompiler.compile_string
|   Warning: Line 1689: Unexpected indentation.
|   
  [...........................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| mof_compiler.py, line 1422, in pywbem.mof_compiler._print_logger
|   Warning: Line 1423: Unknown target name: "str".
|   
  [.............................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1507, in pywbem.tupleparse.parse_any
|   Warning: Line 1512: Unknown target name: "parse".
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 301, in pywbem.tupleparse.parse_cim
|   Warning: Line 306: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 603, in pywbem.tupleparse.parse_classname
|   Warning: Line 608: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1526, in pywbem.tupleparse.parse_embeddedObject
|   Warning: u'raises' expected a single argument
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1439, in pywbem.tupleparse.parse_error
|   Warning: Line 1443: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1285, in pywbem.tupleparse.parse_expmethodcall
|   Warning: Line 1289: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1362, in pywbem.tupleparse.parse_expparamvalue
|   Warning: Line 1366: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1248, in pywbem.tupleparse.parse_imethodcall
|   Warning: Line 1252: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1195, in pywbem.tupleparse.parse_message
|   Warning: Line 1199: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1267, in pywbem.tupleparse.parse_methodcall
|   Warning: Line 1271: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1405, in pywbem.tupleparse.parse_methodresponse
|   Warning: Line 1408: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 557, in pywbem.tupleparse.parse_namespace
|   Warning: Line 561: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1092, in pywbem.tupleparse.parse_parameter
|   Warning: Line 1096: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1133, in pywbem.tupleparse.parse_parameter_array
|   Warning: Line 1137: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1162, in 
| pywbem.tupleparse.parse_parameter_refarray
|   Warning: Line 1166: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1111, in 
| pywbem.tupleparse.parse_parameter_reference
|   Warning: Line 1115: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 977, in pywbem.tupleparse.parse_property_array
|   Warning: Line 981: Unexpected indentation.
|   
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/
| tupleparse.py, line 1020, in 
| pywbem.tupleparse.parse_property_reference
|   Warning: Line 1024: Unexpected indentation.
|   
  [..............................
+---------------------------------------------------------------------
| File /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/wbemcli.py,
| line 154, in pywbem.wbemcli.GetInstance
|   Warning: @param for unknown parameter "IncludeQualifier"
|   Warning: u'raises' expected a single argument
|   
  [.........................................................................
Warning: Failed identifier crossreference targets:
         - 'instance'
               (from pywbem.cim_obj.CIMProperty.__init__)
         - 'object'
               (from pywbem.cim_obj.CIMProperty.__init__)
         - 'uint8'
               (from pywbem.cim_obj.CIMProperty.__init__)
         - CIMProperty(&quot;MyEmbObj&quot;, CIMInstance(...),
         embedded_object='object')
               (from pywbem.cim_obj.CIMProperty.__init__)
         - EmbeddedInstance
               (from pywbem.cim_obj.CIMProperty.__init__)
         - EmbeddedObject
               (from pywbem.cim_obj.CIMProperty.__init__)
         - M2Crypto
               (from pywbem.cim_operations.WBEMConnection.__init__)
         - M2Crypto.SSL.Connection
               (from pywbem.cim_operations.WBEMConnection.__init__)
         - M2Crypto.SSL.Context.set_verify
               (from pywbem.cim_operations.WBEMConnection.__init__)
         - OpenSSL.crypto.X509
               (from pywbem.cim_operations.WBEMConnection.__init__)
         - Propagated
               (from pywbem.cim_obj.CIMProperty.__init__)
         - __version__
               (from pywbem)
         - cim_provider
               (from pywbem)
         - cim_provider2
               (from pywbem)
         - classname
               (from pywbem.cim_operations.WBEMConnection.CreateInstance)
         - datetime.datetime
               (from ??.datetime)
               (from pywbem.cim_types)
               (from pywbem.cim_types.CIMDateTime.datetime)
         - datetime.timedelta
               (from ??.timedelta)
               (from pywbem.cim_types)
               (from pywbem.cim_types.CIMDateTime.timedelta)
               (from pywbem.cim_types.MinutesFromUTC.dst)
               (from pywbem.cim_types.MinutesFromUTC.utcoffset)
         - datetime.tzinfo
               (from pywbem.cim_types.CIMDateTime.fromtimestamp)
               (from pywbem.cim_types.CIMDateTime.now)
               (from pywbem.cim_types.MinutesFromUTC)
         - datetime.tzinfo.dst
               (from pywbem.cim_types.MinutesFromUTC.dst)
         - datetime.tzinfo.utcoffset
               (from pywbem.cim_types.MinutesFromUTC.utcoffset)
         - hhmmss
               (from pywbem.cim_types.CIMDateTime.fromtimestamp)
               (from pywbem.cim_types.CIMDateTime.now)
         - namespace
               (from pywbem.cim_operations.WBEMConnection.CreateInstance)
         - path
               (from pywbem.cim_operations.WBEMConnection.CreateClass)
               (from pywbem.cim_operations.WBEMConnection.CreateInstance)
               (from pywbem.cim_operations.WBEMConnection.ExecQuery)
         - properties
               (from pywbem.cim_operations.WBEMConnection.CreateInstance)
         - pywbem.__version__
               (from pywbem)
         - qualifiers
               (from pywbem.cim_operations.WBEMConnection.CreateInstance)
         - twisted
               (from pywbem)
         - twisted_client
               (from pywbem)
         - value
               (from pywbem.cim_obj.CIMProperty)

  [.........................................................................]

**Comment by andy-maier** [comment]
Karl,
these are messages from epydoc, and they have always been there (for Python 2.x, epydic is not invoked on Python 3). See for example the `make builddoc` section of this Travis CI run of v0.8.2: https://travis-ci.org/pywbem/pywbem/jobs/117218033

We never started to fix them, because we knew we were migrating to Sphinx.

I suggest that we just leave them alone. Once we release v0.9.0, my take is we stop maintaining the v0.8.x stream.

**Comment by KSchopmeyer** [comment]
I agree.  Was so used to not seeing them any more that I completely forgot.

Karl
On 04/18/2016 03:18 AM, Andreas Maier wrote:
>
> Karl,
> these are messages from epydoc, and they have always been there (for 
> Python 2.x, epydic is not invoked on Python 3). See for example the 
> |make builddoc| section of this Travis CI run of v0.8.2: 
> https://travis-ci.org/pywbem/pywbem/jobs/117218033
>
> We never started to fix them, because we knew we were migrating to Sphinx.
>
> I suggest that we just leave them alone. Once we release v0.9.0, my 
> take is we stop maintaining the v0.8.x stream.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/pull/225#issuecomment-211259088>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
+1

**Pull request merged**
